<div class="block-notify alert <?php echo $data['TYPE']; ?>">
    <div class="block-header">
        <?php echo $this->l10n->gettext('alert'); ?> 
        <a href="#" id="close-notify">&times;</a>
    </div>

    <div class="block-line"></div>

    <div class="block-content">
        <b><?php echo $data['TITLE']; ?></b> <?php echo $data['MESSAGE']; ?>
    </div>
</div>

<!--
<div class="alert <?php echo $data['TYPE']; ?>" role="alert">
    <h4 class="alert-heading">
        <?php echo $data['TITLE']; ?>
        <button type="button" class="close" id="close-notify" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </h4>
    <p><?php echo $data['MESSAGE']; ?></p>
</div>-->
