<tr>
	<td><?= $data['ID']; ?></td>
	<td><?= $data['LOGIN']; ?></td>
	<td><?= $data['TEXT']; ?></td>
	<td>
		<a href="<?= BASE_URL; ?>?mode=news&id=<?= $data['NID']; ?>" target="_blank"><i class="fa fa-share"></i></a> <?= $data['NEW']; ?>
	</td>
	<td class="action">
		<div class="ui checkbox">
			<input type="checkbox" name="id[]" class="check-input" value="<?= $data['ID']; ?>">
			<label></label>
		</div>
	</td>
</tr>

