<link href="<?php echo STYLE_URL; ?>css/modules/profile/main.css" rel="stylesheet" media="screen">
<script src="<?php echo STYLE_URL; ?>js/modules/profile/main.js"></script>
<link href="<?php echo STYLE_URL; ?>css/jquery.datetimepicker.css" rel="stylesheet" media="screen">
<script src="<?php echo STYLE_URL; ?>js/jquery.datetimepicker.js"></script>
<script src="<?php echo STYLE_URL; ?>js/jquery.address.js"></script>
