<div class="row">
	<div class="column">
		
		<form class="ui form" method="post">
			
			<table class="ui definition table">
				<tbody>
					
					<tr>
						<td class="collapsing">
							<label for="inputLogin"><?= $this->l10n->gettext('login'); ?></label>
						</td>
						<td>
							<input id="inputLogin" name="login" type="text" value="<?= $data['LOGIN']; ?>" placeholder="<?= $this->l10n->gettext('login'); ?>" required>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="inputPassword"><?= $this->l10n->gettext('password'); ?></label>
						</td>
						<td>
							<input id="inputPassword" name="password" type="text" placeholder="<?= $this->l10n->gettext('password'); ?>" required>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="inputEmail"><?= $this->l10n->gettext('email'); ?></label>							
						</td>
						<td>
							<input id="inputEmail" name="email" type="text" value="<?= $data['EMAIL']; ?>" placeholder="<?= $this->l10n->gettext('email'); ?>">
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="selectGid"><?= $this->l10n->gettext('group'); ?></label>					
						</td>
						<td>
							<select class="ui fluid selection dropdown" name="gid" id="selectGid" required>
								<?= $data['GROUPS']; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="selectGender"><?= $this->l10n->gettext('gender'); ?></label>			
						</td>
						<td>
							<select class="ui fluid selection dropdown" name="gender" id="selectGender">
								<option value="0">
									<?= $this->l10n->gettext('gender_n'); ?>
								</option>
								<option value="1" <?= $data['GENDER']; ?>>
									<?= $this->l10n->gettext('gender_m'); ?>
								</option>
								<option value="2" <?= $data['GENDER']; ?>>
									<?= $this->l10n->gettext('gender_w'); ?>
								</option>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="inputMoney"><?= $this->l10n->gettext('money'); ?></label>			
						</td>
						<td>
							<input id="inputMoney" name="money" type="number" step="0.01" value="<?= $data['MONEY']; ?>" placeholder="<?= $this->l10n->gettext('money'); ?>">
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="inputRMoney"><?= $this->l10n->gettext('real_money'); ?></label>	
						</td>
						<td>
							<input id="inputRMoney" name="realmoney" type="number" step="0.01" value="<?= $data['REALMONEY']; ?>" placeholder="<?= $this->l10n->gettext('realmoney'); ?>">
						</td>
					</tr>
					
				</tbody>
			</table>
			
			<button type="submit" class="ui huge fluid primary button" name="submit"><?= $data['BUTTON']; ?></button>
			
		</form>
		
	</div>
</div>
