<div class="form-block">

	<div class="block-header">
		<div class="block-name"><?php echo $data['PAGE']; ?></div>
	</div>

	<div class="block-line"></div>

	<form method="post">
		<div class="form-group">
			<label for="inputLogin"><?php echo $this->l10n->gettext('login'); ?></label>
			<input type="text" class="form-control" name="login" value="<?php echo $data['LOGIN']; ?>" id="inputLogin" placeholder="<?php echo $this->l10n->gettext('login'); ?>">
		</div>

		<div class="form-group">
			<label for="inputPassword"><?php echo $this->l10n->gettext('password'); ?></label>
			<input type="text" class="form-control" name="password" id="inputPassword" placeholder="<?php echo $this->l10n->gettext('pass'); ?>">
		</div>

		<div class="form-group">
			<label for="inputEmail"><?php echo $this->l10n->gettext('email'); ?></label>
			<input type="text" class="form-control" name="email" value="<?php echo $data['EMAIL']; ?>" id="inputEmail" placeholder="<?php echo $this->l10n->gettext('email'); ?>">
		</div>

		<div class="form-group">
			<label for="selectGid"><?php echo $this->l10n->gettext('group'); ?></label>
			<select name="gid" class="form-control" id="selectGid">
				<?php echo $data['GROUPS']; ?>
			</select>
		</div>

		<div class="form-group">
			<label for="selectGender"><?php echo $this->l10n->gettext('gender'); ?></label>
			<select name="gender" class="form-control" id="selectGender">
				<option value="0"><?php echo $this->l10n->gettext('gender_n'); ?></option>
				<option value="1"
				<?php echo $data['GENDER']; ?>><?php echo $this->l10n->gettext('gender_m'); ?></option>
				<option value="2"
				<?php echo $data['GENDER']; ?>><?php echo $this->l10n->gettext('gender_w'); ?></option>
			</select>
		</div>

		<div class="form-group">
			<label for="inputMoney"><?php echo $this->l10n->gettext('money'); ?></label>
			<input type="text" class="form-control" name="money" value="<?php echo $data['MONEY']; ?>" id="inputMoney" placeholder="<?php echo $this->l10n->gettext('money'); ?>">
		</div>

		<div class="form-group">
			<label for="inputRMoney"><?php echo $this->l10n->gettext('real_money'); ?></label>
			<input type="text" class="form-control" name="realmoney" value="<?php echo $data['REALMONEY']; ?>" id="inputRMoney" placeholder="<?php echo $this->l10n->gettext('realmoney'); ?>">
		</div>

		<button type="submit" class="btn btn-block btn-primary" name="submit"><?php echo $data['BUTTON']; ?></button>
	</form>

</div>