<div class="row">
	<div class="column">
		<div id="mcr-dashboard" class="ui segment">

			<h3 class="ui inverted header">
				О MagicMCR
				<div class="content">
					<h5 class="ui grey header">Спасибо за установку MagicMCR</h5>
					<div class="sub header">
						<p>
							MagicMCR является отдельным и независимым продуктом.
							Использование исходного кода регламентируется, согласно
							<a href="https://github.com/jm-organization/webmcr_gm_edition/blob/master/LICENSE" class="card-link custom">GNU General Public License v3.0</a>.
							MagicMCR не является копией оригинального движка WebMCR, а лишь его подверсией. Разработка MagicMCR производится исключительно в частных интересах.
							Разработчики, а также лица, участвующие в разработке и поддержке, не несут ответственности за проблемы, возникшие с движком.<br>
						</p>
					</div>
				</div>
			</h3>

			<div class="ui section divider"></div>

			<h5 class="ui inverted header">Состояние системы</h5>
			<div class="ui secondary segment" style="background:#ffffff1a;border-radius:4px;">
				<div class="ui small horizontal labels">
					<span style="color: red;"><?= $this->l10n->gettext('system_errors') ?>: <span class="ui red label"><?= $this->log->get_logs_num('error') ?></span></span>
					<span style="color: orange;"><?= $this->l10n->gettext('system_warnings') ?>: <span class="ui orange label"><?= $this->log->get_logs_num('warning') ?></span></span>
					<span style="color: blue;"><?= $this->l10n->gettext('system_noties') ?>: <span class="ui blue label"><?= $this->log->get_logs_num('notice') ?></span></span>
				</div>
			</div>

		</div>
	</div>
</div>

<div class="two column row">
	<div class="column">
		<? if (!empty($data['MODULES'])) { ?>
		<?= $data['MODULES'] ?>
		<? } ?>
		<?= $data['THEMES'] ?>
	</div>
	<div class="column">
		<?= $data['USERS'] ?>
	</div>
</div>
