<?php foreach ($messages as $message) {
    ?>

    <div class="block-notify form-block alert alert-<?= $message['message_type'] ?>">
        <div class="block-header" style="color: unset">
			<?= translate('alert') ?>
            <a href="#" id="close-notify">&times;</a>
        </div>

        <div class="block-line"></div>

        <div class="block-content">
            <b><?= $message['message_title'] ?></b> <?= $message['message_content'] ?>
        </div>
    </div>

    <?php
}
