<div class="ui segments">
  <div class="ui segment">
		<h5 class="ui header">
			<i class="fa fa-plus-square"></i>
			<?= $this->l10n->gettext('modules') ?> <a href="/?mode=admin&do=modules" class="fa fa-link"></a>
		</h5>
	</div>
  <div class="ui segment admin-menu-groups">
		<div class="spl-body owl-carousel owl-theme" id="modules_carusel">
			<? foreach ($data as $datum) { ?>
				<div class="item">
					<a href="<?= $datum['url']; ?>" title="<?= $datum['text']; ?>" target="<?= $datum['target']; ?>">
						<div class="i-icon" style="background: url(<?= UPLOAD_URL; ?>panel-icons/<?= $datum['img'] ?>);"></div>
						<?= $datum['title']; ?>
					</a>
				</div>
			<? } ?>
		</div>
	</div>
</div>
