<div class="ui segments">
  <div class="ui segment">
		<i class="fa fa-th-large"></i> <?= $this->l10n->gettext('themes') ?>
	</div>
	
  <div class="ui segment admin-themes-menu">
		<div class="owl-carousel owl-theme" id="themes_carusel">
			<?= $data['CONTENT'] ?>
		</div>
	</div>
	
	<!--  THEME MODAL  -->
	
	<div id="themesModal" class="ui modal">
		<div class="modal-header header">
			<h2 class="modal-title">
				<span class="theme-name"></span>
			</h2>
		</div>
		
		<div class="ui top attached tabular menu" id="themes_tabs">
			<a class="active item" id="about-tab" data-tab="about"><?= $this->l10n->gettext('about_theme') ?></a>
			<a class="item" id="screenshots-tab" data-tab="screenshots"><?= $this->l10n->gettext('themes_screenshots') ?></a>
		</div>
		
		<div class="scrolling content">
			
			<div id="themes_tabs_content">
				<div class="ui active tab" id="about" data-tab="about">
					<div class="row">
						<div class="col-md-8">
							<h2>
								<?= $this->l10n->gettext('about_theme') ?> <span class="theme-name"></span>
							</h2>
							<hr>
							<div class="about-theme"></div>
						</div>
						<div class="col-md-4" style="background: #f7f7f9;margin: -15px 0;border-left: 1px solid #ddd;padding: 15px;">
							<p class="theme-version">
								<i class="fa fa-info-circle theme-version-info mr-2"
								title="<?= $this->l10n->gettext('magicmer_theme_version_info') ?>" data-container="body" data-toggle="popover" data-placement="bottom" data-content=""
								style="cursor:pointer;"
								></i>
								<b><?= $this->l10n->gettext('magicmer_theme_version') ?>:</b> <span></span>
							</p>
							<p class="theme-supported-magicmcr-version"><b><?= $this->l10n->gettext('magicmer_theme_mcr_supported_version') ?>:</b> <span></span></p>
							<p class="theme-date-created"><b><?= $this->l10n->gettext('magicmer_theme_date_create') ?>:</b> <span></span></p>
							<p class="theme-date-of-last-release"><b><?= $this->l10n->gettext('magicmer_theme_date_last_release') ?>:</b> <span></span></p>
							<p class="theme-update-url"><b><?= $this->l10n->gettext('magicmer_theme_up_url') ?>:</b> <span></span></p>
							
							<hr>
							
							<p class="theme-author"><b><?= $this->l10n->gettext('magicmer_theme_author') ?>:</b> <span></span></p>
							<p class="theme-author-url"><b><?= $this->l10n->gettext('magicmer_theme_author_url') ?>:</b> <span></span></p>
						</div>
					</div>
				</div>
				
				<div class="ui tab" id="screenshots" data-tab="screenshots">
					<div id="lightgallery"></div>
				</div>
			</div>
			
			<div class="actions">
				<button type="button" class="ui positive button" id="theme_install"><?= $this->l10n->gettext('patch_install') ?></button>
			</div>
			
		</div>
	</div>
	
</div>
