<form method="post" class="panel-news" action="<?= ADMIN_URL; ?>&do=news&op=delete">
	<div class="form-block">

		<div class="block-header">
			<div class="block-name">
				<p id="title">
					<span class="title"><?= $this->l10n->gettext('news'); ?></span>
				</p>
				<p id="actions">
					<span class="btn-group" role="group">
                    	<a role="button" href="<?= ADMIN_URL.'&do=news&op=add'; ?>" class="btn btn-primary"><?= $this->l10n->gettext('news_add'); ?></a>
                    </span>
				</p>
			</div>
		</div>

		<div class="block-line"></div>

		<table class="magic-datatables table table-hover" id="news_list">
			<thead>
				<tr>
					<th class="news-id">#</th>
					<th class="news-title"><?= $this->l10n->gettext('news_field_name'); ?></th>
					<th class="news-category"><?= $this->l10n->gettext('news_field_cat'); ?></th>
					<th class="news-action sorting_disabled"><?= $this->l10n->gettext('action'); ?>
						<input type="checkbox" class="check-all" data-for="check-input"></th>
				</tr>
			</thead>

			<tbody>
				<?= $data['NEWS']; ?>
			</tbody>
		</table>
	</div>
</form>