<div class="form-block new-full">

	<div class="block-header">

		<div class="block-name">
			<h4 style="color: #484848"><?= $data['TITLE']; ?>
				<small style="display: block; font-size: 65%">(<?= $this->l10n->gettext('news_prew_page_name'); ?>)</small>
			</h4>
		</div>

		<div class="block-right">
			<?= $data['LIKES']; ?>
		</div>
	</div>

	<div class="block-line"></div>

	<div class="new-full-content">
		<?= $data['TEXT']; ?>
	</div>

	<div class="block-line"></div>

	<div class="block-footer">
		<? if ($data['PLANED_PUBLISH']) { ?>
			<?= $data['PLANED_PUBLISH']; ?>
		<? } ?>
		<div class="category">
			<a target="_blank" href="<?= BASE_URL; ?>?mode=news&amp;cid=<?= $data['CID']; ?>" rel="tooltip" title="Категория"><?= $data['CATEGORY']; ?></a>
		</div>
		<div class="readmore">
			<a target="_blank" href="<?= BASE_URL; ?>"><?= $this->l10n->gettext('news_go_home'); ?></a></div>
		<div class="views" rel="tooltip" title="<?= $this->l10n->gettext('news_field_views'); ?>">
			<i class="fa fa-eye"></i>0
		</div>
	</div>

</div>
