<?= $data['PREVIEW']; ?>

<div class="row">
	<div class="column">
		
		<form class="ui form" method="post">
			<div class="required field">
				<label for="inputTitle"><?= $this->l10n->gettext('news_field_name'); ?></label>
				<input type="text" name="title" required="required" value="<?= $data['TITLE']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('news_field_name'); ?>">
			</div>
			
			<div class="field">
				<label for="inputCategory"><?= $this->l10n->gettext('news_field_cat'); ?></label>
				<select class="ui fluid selection dropdown" id="inputCategory" name="cid"><?= $data['CATEGORIES']; ?></select>
			</div>
			
			<div class="equal width fields" id="label_pp">
				<div class="field">
					<?= $this->l10n->gettext('news_field_date'); ?>
				</div>
				<div class="one wide field">
					<div class="ui toggle checkbox" id="planed_publish">
						<input type="checkbox" name="planed_publish" value="1" <?= $data['PLANED_PUBLISH']; ?>>
						<label></label>
					</div>
				</div>
			</div>
			
			<div class="field">
				<div class="date-publish" id="date_publish">
					<input type="text" name="publish_time" id="input_publish_time" placeholder="<?= $this->l10n->gettext('news_field_d_ph'); ?>" value="<?= $data['DATE']; ?>">
				</div>
			</div>
			
			<div class="field">
				<label for="inputText"><?= $this->l10n->gettext('news_field_text'); ?></label>
				<textarea id="inputText" class="tinymce bb-textarea input-block-level" data-for="bb-full" name="text" rows="20"><?= $data['TEXT']; ?></textarea>
				<small id="textHelp" class="form-text text-muted"><?= $this->l10n->gettext('news_field_text_desc'); ?></small>
			</div>
			
			<div class="equal width fields">
				<div class="field">
					<?= $this->l10n->gettext('news_field_hidden'); ?>
				</div>
				<div class="one wide field">
					<div class="ui toggle checkbox">
						<input type="checkbox" name="hidden" value="1" <?= $data['HIDDEN']; ?>>
						<label></label>
					</div>
				</div>
			</div>
			
			<div class="equal width fields">
				<div class="field">
					<?= $this->l10n->gettext('news_field_vote'); ?>
				</div>
				<div class="one wide field">
					<div class="ui toggle checkbox">
						<input type="checkbox" name="vote" value="1" <?= $data['VOTE']; ?>>
						<label></label>
					</div>
				</div>
			</div>
			
			<div class="equal width fields">
				<div class="field">
					<?= $this->l10n->gettext('news_field_com'); ?>
				</div>
				<div class="one wide field">
					<div class="ui toggle checkbox">
						<input type="checkbox" name="discus" value="1" <?= $data['DISCUS']; ?>>
						<label></label>
					</div>
				</div>
			</div>
			
			<div class="equal width fields">
				<div class="field">
					<?= $this->l10n->gettext('news_field_attach'); ?>
				</div>
				<div class="one wide field">
					<div class="ui toggle checkbox">
						<input type="checkbox" name="attach" value="1" <?= $data['ATTACH']; ?>>
						<label></label>
					</div>
				</div>
			</div>
			
			<!--<hr>
				
				<div class="field">
				
				<p id="label_sc" style="display: inline-block; width: 100%">
				<span style="float: left; line-height: 24px;"><?= $this->l10n->gettext('news_field_comment_close'); ?></span>
				<label style="float: right;" id="switch_sc" class="switch">
				<input type="checkbox" name="closed_comments" value="1">
				<span class="slider round"></span>
				</label>
				</p>
				<div class="date_cs" id="date_cs">
				<input type="text" name="date_cs" id="input_date_cs" placeholder="<?= $this->l10n->gettext('news_field_cc_ph'); ?>" data-start="<?= date('d.m.Y', time());?>" value="">
				</div>
				</div>
				</div>
				
				<div class="field">
				<div class="form-group col-md-4">
				<label for="comment_chars" class="col-form-label">Email</label>
				<input type="email" id="comment_chars" name="comment_chars" placeholder="">
				<small class="form-text text-muted">kek</small>
				</div>
				
				<div class="form-group col-md-3">
				<label for="comment_chars" class="col-form-label">frequency</label>
				<input type="email" id="comment_frequency" name="comment_fq" placeholder="">
				</div>
				
				<div class="form-group col-md-5">
				<label for="comment_chars" class="col-form-label">user group</label>
				<div class="input-group">
				<select name="user_group">
				<option selected disabled>Select this</option>
				<?= $data['USER_GROUPS']; ?>
				</select>
				<span class="input-group-addon" id="basic-addon2">и выше.</span>
				</div>
				<small class="form-text text-muted">kek</small>
				</div>
			</div>-->
			
			<div class="field">
				
				<div class="ui fluid huge buttons">
					<button class="ui primary button" type="submit" name="submit"><?= $data['BUTTON']; ?></button>
					<button class="ui primary button" type="submit" name="preview"><?= $this->l10n->gettext('news_preview'); ?></button>
				</div>
				
			</div>
			
		</form>
		
	</div>
</div>


<div class="row">
	<div class="column">
		<?= $this->file_manager(); ?>
	</div>
</div>
