<div class="ui segments">

    <div class="ui segment">
        <div class="header"><i class="icon user"></i> <?= translate('auth') ?></div>
    </div>

    <div class="ui secondary segment">

        <form class="ui form" method="post" action="<?= url('auth.login') ?>?mode=auth">

            <div class="field">
                <input type="text" id="login" name="login" class="form-control" placeholder="<? translate('login_or_email') ?>">
            </div>

            <div class="relative field">
                <input type="password" id="password" name="password" class="form-control" placeholder="<?= translate('password') ?>">
                <span id="restore">
                    <a href="<?= url('auth.restore') ?>"><?= translate('restore') ?></a>
                </span>
            </div>

            <div class="field">
                <div class="ui checked checkbox">
                    <input type="checkbox" checked  id="remember" name="remember" value="1">
                    <label for="remember"><?= translate('remember') ?></label>
                </div>
            </div>

            <button class="ui fluid primary button" type="submit" name="submit" value="1"><?= translate('sign_in') ?></button>
	        <p class="center-align">
		        <?= translate('or') ?> <a href="<?= url('auth.register') ?>"><?= translate('register') ?></a>
            </p>
        </form>

    </div>

</div>