<div class="form-block">
	
	<div class="block-header"><?= translate('auth') ?></div>
	
	<div class="block-line"></div>
	
	<div class="block-content">
		<form method="post" class="block-auth" action="<?= BASE_URL ?>?mode=auth">
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-user"></i></span>
					<input type="text" name="login" class="form-control" placeholder="<? translate('login_or_email') ?>">
				</div>
			</div>
			
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-lock"></i></span>
					<input type="password" name="password" class="form-control" placeholder="<?= translate('password') ?>">
				</div>
			</div>
			
			<label class="custom-control custom-checkbox">
				<input class="custom-control-input" type="checkbox" name="remember" value="1">
				<span class="custom-control-indicator"></span>
				<span class="custom-control-description"><?= translate('remember') ?></span>
			</label>
			
			<div class="row">
				<div class="col-md-4">
                    <button type="submit" class="btn btn-secondary btn-block"><?= translate('sign_in') ?></button>
                </div>
				<div class="col-md-3">
                    <a class="btn btn-secondary btn-block" rel="tooltip" title="<?= translate('restore') ?>" href="<?= BASE_URL ?>?mode=restore"><i class="fa fa-repeat"></i></a>
                </div>
				<div class="col-md-5">
                    <a href="<?= BASE_URL ?>?mode=register" class="btn btn-secondary btn-block"><?= translate('register') ?></a>
                </div>
			</div>
		</form>
	</div>
	
</div>