<div class="form-block">
	
	<div class="block-header"><?= translate('miniprofile') ?></div>
	
	<div class="block-line"></div>
	
	<div class="block-content">
		<form class="block-profile" method="post" action="<?= BASE_URL ?>?mode=logout">
            <div class="avatar"><img src="<?php /*echo SKIN_URL; ?>interface/<?php echo $this->user->skin; ?>_mini.png?<?php echo mt_rand(1000,9999);*/ ?>" class="img-polaroid"></div>
			<ul class="info">
				<li><i class="fa fa-user"></i> <b><?= translate('login') ?>:</b> NULL</li>
				<li><i class="fa fa-users"></i> <b><?= translate('group') ?>:</b> NULL</li>
				<li><i class="fa fa-money"></i> <b><?= translate('balance') ?>:</b> NULL <?= translate('cur_game') ?></li>
				<li><a href="<?= BASE_URL ?>?mode=profile" class="btn btn-secondary btn-block btn-sm"><?= translate('settings') ?></a></li>
				<li><button type="submit" name="logout" value="1" class="btn btn-secondary btn-block btn-sm"><?= translate('logout') ?></button></li>
			</ul>
		</form>
	</div>
	
</div>