<?php use mcr\auth\auth; ?>

<div class="ui fluid card">
    <div class="content">
        <img class="right floated mini ui image" src="<?= SKIN_URL ?>interface/<?= auth::user()->skin; ?>_mini.png?<?= mt_rand(1000,9999); ?>">
        <div class="header"><?= auth::user()->login ?></div>
        <div class="meta"><?= auth::user()->group ?></div>
        <div class="description">
            <div class="ui two column centered grid">
                <div class="three column centered row">
                    <div class="wide column"><b><?= translate('balance') ?></b></div>
                    <div class="wide column"><i><?= auth::user()->money ?> <?= translate('cur_game') ?></i></div>
                </div>
            </div>
        </div>
    </div>
    <div class="extra content">
        <form method="post" action="<?= url('auth.logout') ?>">
            <div class="ui two buttons">
                <div class="ui basic primary button"><?= translate('settings') ?></div>
                <button class="ui basic secondary button" name="logout" value="1"><?= translate('logout') ?></button>
            </div>
        </form>
    </div>
</div>