<div class="form-block static-page">

	<div class="block-header">
		<div class="block-name"><?php echo $data['TITLE']; ?></div>
	</div>

	<div class="block-line"></div>

	<div class="static-content">
		<?php echo $data['TEXT']; ?>
	</div>

	<div class="block-line"></div>

	<div class="block-footer">
		<div class="date" rel="tooltip" title="<?php echo $this->l10n->gettext('date_create'); ?>"><?php echo date("d.m.Y", $data['DATA']['time_create']); ?></div>
		<div class="time" rel="tooltip" title="<?php echo $this->l10n->gettext('time_create'); ?>"><?php echo date("H:i", $data['DATA']['time_create']); ?></div>
		<div class="readmore"><a href="<?php echo BASE_URL; ?>"><?php echo $this->l10n->gettext('go_home'); ?></a></div>
	</div>

</div>