<div class="ui grid">
	<div class="four wide column">
		<div class="ui vertical fluid menu" id="v-pills-tab">
			<?= $data['TABS']; ?>
		</div>
	</div>
	<div class="twelve wide stretched column" id="v-pills-tabContent">
		<div class="ui segment">
			<p id="actions" class="ui right floated buttons" role="group">
				<a role="button" href="<?= ADMIN_URL; ?>&do=menu_adm&op=add" class="ui primary button">
					<?= $this->l10n->gettext('add'); ?>
				</a>
			</p>

			<?= $data['GROUPS']; ?>

		</div>
	</div>
</div>
