<div class="row">
	<div class="column">

		<form class="ui form" method="post" action="<?= ADMIN_URL; ?>&do=l10n_languages&op=delete">
			
			<table class="ui selectable celled table" id="languages">
				<thead>
					<tr>
						<th class="l10n-languages"><?= $this->l10n->gettext('languages_list'); ?></th>
						<th class="l10n-action"><?= $this->l10n->gettext('action'); ?></th>
					</tr>
				</thead>
				<tbody>
					<?= $data['LANGUAGES_LIST']?>
				</tbody>
			</table>
			
			<div id="actions" class="ui fluid buttons" role="group">
				<a class="ui primary button" role="button" href="<?= ADMIN_URL.'&do=l10n_languages&op=add'; ?>">
					<?= $this->l10n->gettext('language_add'); ?>
				</a>
				<button type="submit" class="ui negative button"><i class="icon trash" aria-hidden="true"></i></button>
			</div>
			
		</form>

	</div>
</div>
