<link href="<?= STYLE_URL; ?>css/modules/users/global.css" rel="stylesheet" media="screen">
<script src="<?= LANG_URL; ?>js/modules/users/users.js"></script>
<script src="<?= STYLE_URL; ?>js/modules/users/global.js"></script>
<script src="<?= STYLE_URL; ?>js/wysibb/jquery.wysibb.min.js"></script>
<script src="<?= STYLE_URL; ?>js/wysibb/lang/ru.js"></script>
<link rel="stylesheet" href="<?= STYLE_URL; ?>js/wysibb/theme/default/wbbtheme.css"/>
