<div class="ui segments mod-users-list">

	<div class="ui segment mod-users-content">
		<div class="ui search" id="users-search">
			<div class="ui left icon fluid action input">
				<i class="search icon"></i>
				<input class="search-user ac_users" type="text" placeholder="<?= $this->l10n->gettext('search_placeholder'); ?>">
				<button class="ui basic button" type="button"><i class="icon fitted search"></i></button>
			</div>
		</div>

		<table class="ui striped selectable table">
			<thead>
				<tr>
					<th><?= $this->l10n->gettext('avatar'); ?></th>
					<th><?= $this->l10n->gettext('login'); ?></th>
					<th><?= $this->l10n->gettext('group'); ?></th>
					<th><?= $this->l10n->gettext('date_registration'); ?></th>
					<th><?= $this->l10n->gettext('gender'); ?></th>
				</tr>
			</thead>

			<tbody>
				<?= $data['USERS']; ?>
			</tbody>
		</table>

		<?= $data['PAGINATION']; ?>
	</div>

</div>
