<div class="form-block">

	<div class="block-header"><?= translate('online'); ?></div>

	<div class="block-line"></div>

	<div class="block-content">
		<div class="block-online">
			<div class="title"><?= translate('online_now'); ?></div>
			<div id="onl_list"><?= translate('loading'); ?></div>
			<div id="onl_count">
				<p><?= translate('count_all'); ?>: <span id="onl_all">0</span></p>
				<p><?= translate('users'); ?>: <span id="onl_users">0</span>, <?= translate('online_guests'); ?>: <span id="onl_guests">0</span></p>
			</div>

		</div>
	</div>

</div>