<div class="form-block static-page">

	<div class="block-header">
		<div class="block-name"><?= $data['TITLE']; ?></div>
	</div>

	<div class="block-line"></div>

	<div class="static-content">
		<?= $data['TEXT']; ?>
	</div>

	<div class="block-line"></div>

	<div class="block-footer">
		<div class="date" rel="tooltip" title="<?= $this->l10n->gettext('date_create'); ?>"><?= date("d.m.Y", $data['DATA']['time_create']); ?></div>
		<div class="time" rel="tooltip" title="<?= $this->l10n->gettext('time_create'); ?>"><?= date("H:i", $data['DATA']['time_create']); ?></div>
		<div class="readmore"><a href="<?= BASE_URL; ?>"><?= $this->l10n->gettext('go_home'); ?></a></div>
	</div>

</div>