<div class="row">
	<div class="column">

        <h2 class="ui header">
<!--            <img class="ui image" src="--><?//= UPLOAD_URL; ?><!--panel-icons/--><?//= $data['MODULE_IMAGE'] ?><!--">-->
            <div class="content"><?=$this->l10n->gettext('manucp')?></div>
        </h2>

        <form method="post" action="<?= ADMIN_URL; ?>&do=menu_adm&op=delete">
            <div class="ui menu">

                <a class="icon item" href="<?php echo ADMIN_URL; ?>&do=menu_adm&op=add"><i class="add icon"></i>&nbsp;&nbsp;<?php echo $this->l10n->gettext('add'); ?></a>

                <button class="ui icon button item remove" data-for="check-input" data-text="<?php echo $this->l10n->gettext('menu_accept'); ?>" type="submit" name="delete"><i class="trash icon"></i>&nbsp;&nbsp;<?php echo $this->l10n->gettext('delete'); ?></button>

                <div class="right menu">
                    <div class="ui right aligned category search item">
                        <div class="ui transparent icon input">
                            <input class="adm-search-input prompt" id="adm-search-id" type="text" placeholder="<?=$this->l10n->gettext('search_placeholder')?>">
                            <i class="search link icon adm-search" data-for="#adm-search-id"></i>
                        </div>
                        <div class="results"></div>
                    </div>
                </div>

            </div>

            <table class="ui table" style="margin-bottom: 15px;" id="menu_adm">
                <thead>
                <tr>
                    <th class="collapsing"></th>
                    <th>
                        <a href="#" class="black sort-trigger" data-field="title" data-order="desc"><?= $this->l10n->gettext('mcp_field_name'); ?></a>
                    </th>
                    <th>
                        <a href="#" class="black sort-trigger" data-field="group" data-order="desc"><?= $this->l10n->gettext('group'); ?></a>
                    </th>
                    <th class="collapsing action">
                        <div class="ui checkbox" style="float: right">
                            <input type="checkbox" class="check-all" data-for="check-input">
                            <label></label>
                        </div>
                    </th>
                </tr>
                </thead>

                <tbody style="background: #fff">
                <?php foreach ($data['MENU'] as $pages) { ?>
                    <tr>
                        <td style="width: 3%;text-align: center">
                            <input type="checkbox" id="fixed_<?=$pages['ID']?>" <?=$pages['FIXED']?> name="fixed" data-page="<?=$pages['ID']?>" class="align-middle fixed_" value="1" style="display: none">
                            <label for="fixed_<?=$pages['ID']?>" class="paperclip"><i class="paperclip icon"></i></label>
                        </td>
                        <td style="width: 20%;">
                            <a href="<?=$pages['URL']?>" target="<?=$pages['TARGET']?>"><?=$pages['TITLE']?></a>
                        </td>
                        <td><?=$pages['GROUP']?></td>
                        <td class="action" style="display: inline-flex">
                            <a class="ui mini icon button" href="<?=ADMIN_URL?>&do=menu_adm&op=edit&id=<?=$pages['ID'];?>" style="float: right"><i class="pencil icon"></i></a>

                            <div class="ui checkbox" style="float: right; padding: 5px 0 5px 6px;">
                                <input type="checkbox" class="check-input" name="id[]" value="<?=$pages['ID']?>">
                                <label></label>
                            </div>
                        </td>
                    </tr>
                <? } ?>
                </tbody>
            </table>
        </form>

		<?php if (!empty($data['PAGINATION'])) {?>
			<?= $data['PAGINATION']; ?>
		<? } ?>
		
	</div>
</div>
