<div class="row">
	<div class="column">
		
		<script>new ClipboardJS('#copylink');</script>
		
		<form class="ui form menu-adm-change" method="post">
			
			<table class="ui definition table">
				<tbody>
					
					<tr>
						<td>
							<label for="title">#page_id</label>
						</td>
						<td>
							<input type="text" <?= $data['EDIT'] ? 'disabled readonly' : '' ?> required name="page_id" value="<?= $data['PAGE_ID'] ?>">
							<label><?= $this->l10n->gettext('menu_page_id_same_with_class'); ?></label>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="page_url"></label>
						</td>
						<td>
                            <?= $this->cfg->main['s_root_full']; ?>?mode=admin&do=<span id="page_url"><?=$data['PAGE_ID'] ?></span>
							<input type="hidden" data-prefix="/?mode=admin&do=" id="page_main_url" name="url" value="/?mode=admin&do=<?= $data['PAGE_ID'] ?>">

                            <a class="circular ui icon mini button"
                               id="copylink"
                               data-tooltip="Copy to clipboard"
                               data-inverted data-mini
                               onclick="return false;"
                               data-prefix="<?= $this->cfg->main['s_root_full']; ?>?mode=admin&do="
                               data-clipboard-text="<?= $this->cfg->main['s_root_full']; ?>?mode=admin&do=<?= $data['PAGE_ID'] ?>"
                               style="margin-left: 15px"
                            >
                                <i class="clipboard icon"></i>
                            </a>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="menuTitle"><?= $this->l10n->gettext('mcp_field_name'); ?></label>
						</td>
						<td>
							<input type="text" id="menuTitle" name="title" value="<?= $data['TITLE'] ?>">
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="selectGid"><?= $this->l10n->gettext('group') ?></label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" name="gid" id="selectGid">
								<?= $data['GROUPS'] ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="selectPerm"><?= $this->l10n->gettext('mcp_field_access') ?></label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" name="gid" id="selectGid">
								<?= $data['GROUPS'] ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="selectPerm"><?= $this->l10n->gettext('mcp_field_access') ?></label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" name="permissions" id="selectPerm">
								<?= $data['PERMISSIONS'] ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td>
							<label><?= $this->l10n->gettext('mcp_field_icon') ?></label>
						</td>
						<td>
							<img src="" width="36" height="36" class="img-thumbnail" id="menu_icon" style="height:36px;float:left;margin-right:15px;">
								
                            <button id="select_menu_adm_icon" type="button" data-target="#icons-list" class="ui button"><?= $this->l10n->gettext('select_icon') ?></button>


							<div class="ui grid menu-icons-select" id="icons-list">

								<div class="ui header" style="margin-top: 10px;"><?= $this->l10n->gettext('icons') ?></div>
								
								<? foreach ($data['ICONS'] as $icons_chank) { ?>
									<div class="row">
										<? foreach ($icons_chank as $icon) {?>
											<label class="menu-icon column" title="<?= $icon['TITLE']; ?>">
												<input class="icon-input" type="radio" name="icon" data-icon="<?= UPLOAD_URL; ?>panel-icons/<?= $icon['IMG']; ?>" value="<?= $icon['ID']; ?>" <?= $icon['CHECKED']; ?>>
												<div class="icon-img" style="background-image: url(<?= UPLOAD_URL; ?>panel-icons/<?= $icon['IMG']; ?>);"></div>
											</label>
										<? }?>
									</div>
								<? }?>
								
							</div>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="inputPriority"><?= $this->l10n->gettext('mcp_field_priority') ?></label>
						</td>
						<td>
							<input type="number" name="priority" value="<?=$data['PRIORITY']?>" id="inputPriority">
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="selectTarget"><?= $this->l10n->gettext('mcp_field_target') ?></label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" id="selectTarget" name="target">
								<option value="_self"><?= $this->l10n->gettext('mcp_target_self') ?></option>
								<option value="_blank"<?= $data['TARGET']?>><?= $this->l10n->gettext('target_blank2') ?></option>
							</select>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="text"><?= $this->l10n->gettext('mcp_field_desc') ?></label>
						</td>
						<td>
							<textarea id="text" name="text" rows="8" maxlength="255"><?= $data['TEXT'] ?></textarea>
						</td>
					</tr>
					
				</tbody>

                <tfoot class="full-width">

                    <tr>
                        <th></th>
                        <th>
                            <button type="submit" class="ui medium primary button"><?= $this->l10n->gettext('save'); ?></button>
                        </th>
                    </tr>

                </tfoot>

			</table>
			
		</form>
		
	</div>
</div>
