<div class="ui segments">
	
	<div class="ui segment">
		<?= $this->l10n->gettext('add_comment'); ?>
	</div>
	
	<div class="ui segment comment-form">
		<div class="comment-form-content">
			<form class="ui form" method="post">

				<div class="field">
					<textarea id="wysibb-editor" class="wysibb-texarea" rows="7" name="message" data-for="bb-comments" placeholder="<?= $this->l10n->gettext('message'); ?>" required></textarea>
				</div>
				
				<div class="field">
					<button type="submit" class="ui fluid primary huge button" id="add_comment"><?= $this->l10n->gettext('add'); ?></button>
				</div>
				
			</form>
		</div>
	</div>
	
</div>
