<div class="form-block menu-icon-change">

	<div class="block-header">
		<div class="block-name"><?= $data['PAGE']; ?></div>
	</div>

	<div class="block-line"></div>

	<form method="post">
		<div class="form-group">
			<label for="inputTitle"><?= $this->l10n->gettext('mi_field_name'); ?></label>
			<input type="text" class="form-control" name="title" value="<?= $data['TITLE']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('mi_field_name'); ?>" required>
		</div>

		<div class="form-group">
			<label for="inputImg"><?= $this->l10n->gettext('mi_field_img'); ?></label>
			<input type="text" class="form-control" name="img" value="<?= $data['IMG']; ?>" id="inputImg" placeholder="<?= $this->l10n->gettext('mi_field_img'); ?>">
		</div>

		<button type="submit" class="btn btn-primary btn-block" name="submit"><?= $data['BUTTON']; ?></button>
	</form>

</div>