<p><?php echo $this->l10n->gettext('msg1'); ?></p>
<br>
<p><?php echo $this->l10n->gettext('msg2'); ?> "<b><?php echo $data['SITENAME']; ?></b>" (<a href="<?php echo $data['SITEURL']; ?>" target="_blank" title="<?php echo $this->l10n->gettext('target_blank'); ?>"><?php echo $data['SITEURL']; ?></a>)</p>
<p><?php echo $this->l10n->gettext('msg3'); ?></p>
<p><a href="<?php echo $data['LINK']; ?>" target="_blank" title="<?php echo $this->l10n->gettext('target_blank'); ?>"><?php echo $data['LINK']; ?></a></p>
<br>
<p><?php echo $this->l10n->gettext('msg4'); ?></p>
<br><br>
<p><?php echo $this->l10n->gettext('msg4'); ?> "<b><?php echo $data['SITENAME']; ?></b>" (<a href="<?php echo $data['SITEURL']; ?>" target="_blank" title="<?php echo $this->l10n->gettext('target_blank'); ?>"><?php echo $data['SITEURL']; ?></a>)</p>