<div class="ui segments">
	<div class="ui segment"><?= $this->l10n->gettext('register'); ?></div>
	
	<div class="ui segment mcr-register">
		
		<form class="ui form" method="post">
			
			<div class="field">
				<label for="inputLogin"><?= $this->l10n->gettext('login'); ?></label>
				<input type="text" name="login" id="inputLogin" pattern="^[a-zA-Z0-9-_]{3,}$" maxlength="32" placeholder="<?= $this->l10n->gettext('login'); ?>" required>
			</div>
			
			<div class="field">
				<label for="inputEmail"><?= $this->l10n->gettext('email'); ?></label>
				<input type="email" name="email" id="inputEmail" placeholder="<?= $this->l10n->gettext('email'); ?>" required>
			</div>
			
			<div class="field">
				<label for="inputPassword"><?= $this->l10n->gettext('password'); ?></label>
				<input type="password" name="password" id="inputPassword" pattern="^[^']{6,}$" placeholder="<?= $this->l10n->gettext('password'); ?>" required>
			</div>
			
			<div class="field">
				<label for="inputRePassword"><?= $this->l10n->gettext('repass'); ?></label>
				<input type="password" name="repassword" id="inputRePassword" pattern="^[^']{6,}$" placeholder="<?= $this->l10n->gettext('repass'); ?>" required>
			</div>
			
			<div class="field">
				<label for="inputGender"><?= $this->l10n->gettext('gender'); ?></label>
				<select class="ui selection dropdown" name="gender" id="inputGender">
					<option value="0"><?= $this->l10n->gettext('gender_n'); ?></option>
					<option value="1"><?= $this->l10n->gettext('gender_m'); ?></option>
					<option value="2"><?= $this->l10n->gettext('gender_w'); ?></option>
				</select>
			</div>
			
			<?= $this->captcha(); ?>
			
			<div class="field">
				<textarea rows="15" readonly><?= $this->sp("rules.txt"); ?></textarea>
			</div>
			
			<div class="field">
				<div class="ui checkbox">
					<input type="checkbox" name="accept" value="1" required>
					<label class="ui checkbox"><?= $this->l10n->gettext('register_accept'); ?></label>
				</div>
			</div>
			
			<button type="submit" id="postbut" name="submit" class="ui fluid primary huge button"><?= $this->l10n->gettext('sign_up'); ?></button>
		</form>
	</div>
</div>
