<!DOCTYPE HTML>
<html>
	<head>
		<title><?= $this->cfg->main['s_name']; ?> — <?= $this->l10n->gettext('mod_name'); ?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<meta name="description" content="<?= $this->cfg->main['s_about']; ?>">
		<meta name="keywords" content="<?= $this->cfg->main['s_keywords']; ?>">
		<meta name="author" content="NC22 &amp; Qexy.org">
		<meta name='data' content='<?= META_JSON_DATA; ?>'>
		<base href="<?= BASE_URL ?>">
		<?= $this->def_header; ?>
		<?= $this->header; ?>
	</head>

	<body>

		<header class="jumbotron">
			<div class="container">
				<h1><?= $this->cfg->main['s_name']; ?></h1>
				<p>На сайте ведутся технические работы. Вход только для администрации.</p>
			</div>
		</header>

		<?= $this->advice(); ?>

		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div id="js-notify" class="alert alert-warning">
						<a href="#" id="close">&times;</a>
						<div id="title"></div>
						<div id="message"></div>
					</div>

					<div class="form-block">

						<div class="block-header"><?= $this->l10n->gettext('auth'); ?></div>

						<div class="block-line"></div>

						<div class="block-content">
							<form method="post" class="block-auth" action="<?= BASE_URL; ?>?mode=auth">
								<p class="text-center"><?= $data['FOR_TIME']; ?></p>
								<br>

								<div class="form-group">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-user"></i></span>
										<input type="text" name="login" class="form-control" placeholder="<?= $this->l10n->gettext('login'); ?>">
									</div>
								</div>

								<div class="form-group">
									<div class="input-group">
										<span class="input-group-addon"><i class="fa fa-lock"></i></span>
										<input type="password" name="password" class="form-control" placeholder="<?= $this->l10n->gettext('pass'); ?>">
									</div>
								</div>

								<div class="checkbox">
									<label>
										<input type="checkbox" name="remember" value="1">
										<?= $this->l10n->gettext('remember'); ?>
									</label>
								</div>

								<input type="submit" class="btn btn-block btn-primary" name="submit" value="<?= $this->l10n->gettext('enter'); ?>">
							</form>
						</div>

					</div>
				</div>
			</div>
		</div>

		<div id="js-loader" title="Загрузка..."><img src="<?= STYLE_URL; ?>img/loading.gif" alt="Loading..."/></div>

		<nav class="navbar navbar-default navbar-fixed-bottom">
			<div class="container">
				<div id="navbar-footer">
					<div class="navbar-left navbar-text"><?= $this->l10n->gettext('copy_pre'); ?> <?= $this->cfg->main['s_name']; ?> <?= $this->l10n->gettext('copy_app'); ?></div>
					<div class="navbar-right navbar-text"><?= FEEDBACK; ?> | <?= VERSION; ?></div>
				</div>
			</div>
		</nav>

	</body>

</html>