<div class="ui flow">
    <h2 class="ui header">
        <img src="/install/img/logotype.png" style="height:51px;width:auto">
        <div class="content">
            <?= translate('finish_header_title') ?>
            <div class="sub header"><?= translate('installed_success') ?></div>
        </div>
    </h2>

    <p><?= translate('about') ?></p>
    <div class="ui divider"></div>
    <p><?= translate('copyrighting_about') ?></p>

    <div class="ui divider"></div>

    <a class="ui left floated button" href="/install/index.php?reinstall/"><?= translate('reinstall') ?></a>

    <a class="ui right floated next secondary button" href="/"><?= translate('go_home') ?></a>
    <a class="ui right floated button" href="/admin/"><?= translate('go_cp') ?></a>
</div>