<form method="post" class="ui flow form">
    <h3><?= translate('install_progress') ?> - <?= translate('step_3') ?></h3>

    <p style="white-space: pre-line;"><?= translate('install_step_4_desc') ?></p>

    <div class="field">
        <label for="site_name"><?= translate('site_name') ?></label>
        <input type="text" id="site_name" name="site_name" value="<?= old('site_name', config('mcr::site.name')) ?>">
    </div>

    <div class="field">
        <label for="site_about"><?= translate('site_desc') ?></label>
        <input type="text" id="site_about" name="site_about" value="<?= old('site_about', config('mcr::site.description')) ?>">
    </div>

    <div class="field">
        <label for="site_keywords"><?= translate('site_keys') ?></label>
        <input type="text" id="site_keywords" name="site_keywords" value="<?= old('site_keywords', config('mcr::site.keywords')) ?>">
    </div>

    <div class="field">
        <label for="site_url"><?= translate('site_url') ?></label>
        <input type="text" id="site_url" name="site_url" value="<?= old('site_url', \mcr\http\routing\router::base_url()) ?>">
    </div>

    <div class="ui divider"></div>

    <button class="ui right floated next secondary button"><?= translate('next') ?></button>
    <a class="ui right floated button" href="/install/index.php?reinstall/"><?= translate('reinstall') ?></a>
</form>

<script>$('.ui.checkbox').checkbox();</script>