<div class="form-block">

	<div class="block-header">
		<div class="block-name"><?php echo $this->l10n->gettext('set_func'); ?></div>
	</div>

	<div class="block-line"></div>

	<div class="adm-settings">
		<form method="post"></form>

		<ul class="nav nav-tabs">
			<li class="nav-item"><a class="nav-link" href="<?php echo ADMIN_URL; ?>&do=settings&op=main"><?php echo $this->l10n->gettext('set_main'); ?></a></li>
			<li class="nav-item"><a class="nav-link" href="<?php echo ADMIN_URL; ?>&do=settings&op=pagin"><?php echo $this->l10n->gettext('set_pagin'); ?></a></li>
			<li class="nav-item"><a class="nav-link" href="<?php echo ADMIN_URL; ?>&do=settings&op=mail"><?php echo $this->l10n->gettext('set_mail'); ?></a></li>
			<li class="nav-item"><a class="nav-link" href="<?php echo ADMIN_URL; ?>&do=settings&op=search"><?php echo $this->l10n->gettext('set_search'); ?></a></li>
			<li class="nav-item"><a class="nav-link active" href="<?php echo ADMIN_URL; ?>&do=settings&op=functions"><?php echo $this->l10n->gettext('set_func'); ?></a></li>
			<li class="nav-item"><a class="nav-link" href="<?php echo ADMIN_URL; ?>&do=settings&op=base"><?php echo $this->l10n->gettext('set_base'); ?></a></li>
		</ul>
		 
		<div class="tab-content">
			<form method="post">

				<div class="form-group">
					<label for="input_advice"><?php echo $this->l10n->gettext('set_func_advice'); ?></label>
					<select name="advice" class="form-control" id="input_advice">
						<option value="0"><?php echo $this->l10n->gettext('no'); ?></option>
						<option value="1" <?php echo $data['ADVICE']; ?>><?php echo $this->l10n->gettext('yes'); ?></option>
					</select>
				</div>

				<div class="form-group">
					<label for="input_breadcrumbs"><?php echo $this->l10n->gettext('set_funt_bc'); ?></label>
					<select name="breadcrumbs" class="form-control" id="input_breadcrumbs">
						<option value="0"><?php echo $this->l10n->gettext('no'); ?></option>
						<option value="1" <?php echo $data['BREADCRUMBS']; ?>><?php echo $this->l10n->gettext('yes'); ?></option>
					</select>
				</div>

				<div class="form-group">
					<label for="input_close"><?php echo $this->l10n->gettext('set_funt_close'); ?></label>
					<select name="close" class="form-control" id="input_close">
						<option value="0"><?php echo $this->l10n->gettext('no'); ?></option>
						<option value="1" <?php echo $data['CLOSE']; ?>><?php echo $this->l10n->gettext('yes'); ?></option>
					</select>
				</div>

				<div class="form-group">
					<label for="input_close_time"><?php echo $this->l10n->gettext('set_funt_close_time'); ?></label>
					<input type="text" name="close_time" class="form-control" id="input_close_time" value="<?php echo $data['CLOSE_TIME']; ?>">
				</div>

				<button type="submit" name="submit" class="btn btn-primary btn-block"><?php echo $this->l10n->gettext('save'); ?></button>

			</form>
		</div>
	</div>
		
</div>

<script>
	$('#input_close_time').datetimepicker({
		lang:'ru',
		timepicker:true,
		value:'',
		format:'d.m.Y H:i:s'
	});
</script>