<div class="form-block">

	<div class="block-header">
		<div class="block-name"><?php echo $this->l10n->gettext('set_search'); ?></div>
	</div>

	<div class="block-line"></div>

	<div class="adm-settings">
		<form method="post"></form>

		<ul class="nav nav-tabs">
			<li class="nav-item"><a class="nav-link" href="<?php echo ADMIN_URL; ?>&do=settings&op=main"><?php echo $this->l10n->gettext('set_main'); ?></a></li>
			<li class="nav-item"><a class="nav-link" href="<?php echo ADMIN_URL; ?>&do=settings&op=pagin"><?php echo $this->l10n->gettext('set_pagin'); ?></a></li>
			<li class="nav-item"><a class="nav-link" href="<?php echo ADMIN_URL; ?>&do=settings&op=mail"><?php echo $this->l10n->gettext('set_mail'); ?></a></li>
			<li class="nav-item"><a class="nav-link active" href="<?php echo ADMIN_URL; ?>&do=settings&op=search"><?php echo $this->l10n->gettext('set_search'); ?></a></li>
			<li class="nav-item"><a class="nav-link" href="<?php echo ADMIN_URL; ?>&do=settings&op=functions"><?php echo $this->l10n->gettext('set_func'); ?></a></li>
			<li class="nav-item"><a class="nav-link" href="<?php echo ADMIN_URL; ?>&do=settings&op=base"><?php echo $this->l10n->gettext('set_base'); ?></a></li>
		</ul>
		 
		<div class="tab-content">
			<?php echo $data['ITEMS']; ?>
		</div>
	</div>
		
</div>