<div class="form-block">

	<div class="block-header">
		<div class="block-name"><?= $data['PAGE']; ?></div>
	</div>

	<div class="block-line"></div>

	<form method="post">
		<div class="form-group">
			<label class="control-label" for="inputTitle"><?= $this->l10n->gettext('cn_field_name'); ?></label>
			<input type="text" class="form-control" name="title" value="<?= $data['TITLE']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('cn_field_name'); ?>">
		</div>

		<div class="form-group">
			<label class="control-label" for="inputText"><?= $this->l10n->gettext('cn_field_desc'); ?></label>
			<textarea id="inputText" class="form-control" placeholder="<?= $this->l10n->gettext('cn_field_desc'); ?>" name="text" maxlength="255" rows="5"><?= $data['TEXT']; ?></textarea>
		</div>

		<button type="submit" class="btn btn-block btn-primary" name="submit"><?= $data['BUTTON']; ?></button>
	</form>

</div>