<link href="<?php echo STYLE_URL; ?>css/modules/admin/global.css" rel="stylesheet">
<script src="<?php echo STYLE_URL; ?>js/modules/admin/global.js"></script>
<link href="<?php echo STYLE_URL; ?>css/jquery.datetimepicker.css" rel="stylesheet" media="screen">
<script src="<?php echo STYLE_URL; ?>js/jquery.datetimepicker.js"></script>
<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" media="screen">
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>