<div class="form-block mod-users-full">

	<div class="block-header">
		
		<div class="block-name">Профиль пользователя "<?php echo $data['LOGIN']; ?>"</div><!--
		--><div class="block-right">
			<?php echo $data['ADMIN']; ?>
		</div>
	</div>

	<div class="block-line"></div>

	<div class="mod-content">
		<div class="left-block">
			<div class="skin-block">
				<div class="skin-left" style="background-image: url('<?php echo $data['AVATAR']; ?>');"></div>
			</div>

			<div class="skin-block">
				<div class="skin-right" style="background-image: url('<?php echo $data['AVATAR']; ?>');"></div>
			</div>
		</div>

		<div class="right-block">
			<table class="table table-striped table-condensed">
				<tbody>
					<tr>
						<td><b><?php echo $this->l10n->gettext('group'); ?></b></td>
						<td><?php echo $data['GROUP']; ?></td>
					</tr>

					<tr>
						<td><b><?php echo $this->l10n->gettext('gender'); ?></b></td>
						<td><?php echo $data['GENDER']; ?></td>
					</tr>

					<tr>
						<td><b><?php echo $this->l10n->gettext('date_reg'); ?></b></td>
						<td><?php echo $data['DATE_REG']; ?></td>
					</tr>

					<tr>
						<td><b><?php echo $this->l10n->gettext('last_activity'); ?></b></td>
						<td><?php echo $data['DATE_LAST']; ?></td>
					</tr>

					<tr>
						<td><b><?php echo $this->l10n->gettext('money'); ?></b></td>
						<td><?php echo $data['MONEY']; ?> $</td>
					</tr>

					<tr>
						<td><b><?php echo $this->l10n->gettext('realmoney'); ?></b></td>
						<td><?php echo $data['REALMONEY']; ?> руб.</td>
					</tr>

				</tbody>
			</table>
		</div>
	</div>

	<div class="block-line"></div>

	<?php echo $data['COMMENTS']; ?>

</div>