<div class="row">
	<div class="column">
		
		<form class="ui form" method="post">
			<table class="ui definition table">
				
				<thead>
					<tr>
						<th colspan="2"><b><?= $data['TITLE']; ?></b> <?= $data['DESC']; ?></th>
					</tr>
				</thead>
				
				<tbody>
					
					<tr>
						<td class="collapsing">
							<?= $this->l10n->gettext('author'); ?>:
						</td>
						<td>
							<?= $data['AUTHOR']; ?>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<?= $this->l10n->gettext('mod_field_site'); ?>:
						</td>
						<td>
							<a href="<?= $data['SITE']; ?>" target="_blank"><?= $data['SITE']; ?></a>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<?= $this->l10n->gettext('mod_field_email'); ?>:
						</td>
						<td>
							<a href="mailto:<?= $data['EMAIL']; ?>"><?= $data['EMAIL']; ?></a>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<?= $this->l10n->gettext('version'); ?>:
						</td>
						<td>
							<?= $data['VERSION']; ?> <?= $data['UPDATE_RESULT']; ?>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="inputStatus"><?= $this->l10n->gettext('mod_field_status'); ?></label>
						</td>
						<td>
							<select name="status" class="ui fluid selection dropdown" id="inputStatus">
								<option value="0"><?= $this->l10n->gettext('mod_off'); ?></option>
								<option value="1"
								<?= $data['STATUS']; ?>><?= $this->l10n->gettext('mod_on'); ?></option>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="inputUpdate"><?= $this->l10n->gettext('mod_field_upd'); ?></label>
						</td>
						<td>
							<select name="updates" class="ui fluid selection dropdown" id="inputUpdate">
								<option value="0"><?= $this->l10n->gettext('mod_off1'); ?></option>
								<option value="1"
								<?= $data['UPDATE_CHECK']; ?>><?= $this->l10n->gettext('mod_on1'); ?></option>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="inputUrl"><?= $this->l10n->gettext('mod_field_url'); ?></label>
						</td>
						<td>
							<input type="text" id="inputUrl" name="update_url" value="<?= $data['UPDATE_URL']; ?>">
						</td>
					</tr>
					
				</tbody>
			</table>
			
			<button type="submit" class="ui huge fluid primary button" name="submit"><?= $data['BUTTON']; ?></button>
			
		</form>
		
	</div>
</div>
