<div class="comment mcr-comment-id" id="<?= $data['ID']; ?>">
	<div class="content">
		<a class="author"><?= $data['LOGIN']; ?></a>
		<div class="metadata">
			<span data-livestamp="<?= $data['DATA']['time_create']; ?>">
				<?= $this->l10n->parse_date($data['DATA']['time_create']); ?>
			</span>
		</div>
		<div class="text mcr-comment-id-content">
			<?= $data['TEXT']; ?>
		</div>
		<div class="actions">
			<?= $data['ACTION_DELETE']; ?>
			<?= $data['ACTION_EDIT']; ?>
			<?= $data['ACTION_QUOTE']; ?>
		</div>
	</div>
</div>
