<div class="comment" class="comment-id" id="<?= $data['ID']; ?>">
	<div class="content">
		<a class="author"><?= $data['LOGIN']; ?></a>
		<div class="metadata">
			<div class="date" data-tooltip="<?= $this->l10n->gettext('date_create'); ?>">
				<?= date("d.m.Y", $data['DATA']['time_create']); ?>
			</div>
			<div class="date" data-tooltip="<?= $this->l10n->gettext('time_create'); ?>">
				<?= date("H:i:s", $data['DATA']['time_create']); ?>
			</div>
		</div>
		<div class="text">
			<?= $data['TEXT']; ?>
		</div>
		<div class="actions">
			<?= $data['ACTION_DELETE']; ?>
			<?= $data['ACTION_EDIT']; ?>
			<?= $data['ACTION_QUOTE']; ?>
		</div>
	</div>
</div>
