<div class="form-block comment-form">

	<div class="block-header">
		<?php echo $this->l10n->gettext('add_comment'); ?>
	</div>

	<div class="block-line"></div>

	<div class="comment-form-content">
		<form method="post">
			<textarea name="message" id="wysibb-editor" class="form-control wysibb-texarea" data-for="bb-comments" placeholder="<?php echo $this->l10n->gettext('message'); ?>" required></textarea>

			<button type="submit" class="btn btn-block btn-primary" name="comment" id="add_comment" value="add"><?php echo $this->l10n->gettext('add'); ?></button>
		</form>
	</div>
</div>