<div class="form-block">

	<div class="block-header">
		<div class="block-name"><?= $this->lng_m['patches']; ?></div>
	</div>

	<div class="block-line"></div>

	<div class="adm-patch">
		<div class="alert">
			<strong><?= $this->lng['e_attention']; ?></strong> <?= $this->lng_m['warning']; ?>
		</div>

		<form method="post" class="form-horizontal">
			<div class="control-group">
				<label class="control-label" for="inputName"><?= $this->lng_m['name']; ?></label>
				<div class="controls">
					<select name="name" class="span12" id="inputName">
						<?= $data['PATCHES']; ?>
					</select>
				</div>
			</div>

			<div class="text-center">
				<button class="btn btn-success" type="submit"><?= $this->lng_m['install']; ?></button>
			</div>
		</form>

	</div>

</div>
