<div class="row">
	<div class="column">
	
		<div class="form-block static-page">
			
			<div class="block-header">
				<div class="block-name"><?= $data['TITLE']; ?> (<?= $this->l10n->gettext('stc_preview'); ?>)</div>
			</div>
			
			<div class="block-line"></div>
			
			<div class="static-content">
				<?= $data['TEXT']; ?>
			</div>
			
			<div class="block-line"></div>
			
			<div class="block-footer">
				<div class="date" rel="tooltip" title="Дата создания"><?= date("d.m.Y", time()); ?></div>
				<div class="time" rel="tooltip" title="Время создания"><?= date("H:i", time()); ?></div>
				<div class="readmore">
				<a target="_blank" href="<?= BASE_URL; ?>"><?= $this->l10n->gettext('go_home'); ?></a></div>
			</div>
			
		</div>
		
	</div>
</div>
