<p data-format-id="<?php echo $data['ID']; ?>" class="date_format">
	<label class="custom-control custom-radio">
		<input name="<?php echo $data['DT']; ?>_format" type="radio" class="custom-control-input" value="<?php echo $data['FORMAT']; ?>"<?php echo $data['SELECT']; ?>>
		<span class="custom-control-indicator"></span>
		<span class="custom-control-description"><?php echo $data['EXAMPLE']; ?></span>
	</label>
	<small class="form-text text-muted"><?php echo $data['FORMAT']; ?></small>
</p>
