<p data-format-id="<?= $data['ID']; ?>" class="date_format">
	<label class="custom-control custom-radio">
		<input name="<?= $data['DT']; ?>_format" type="radio" class="custom-control-input" value="<?= $data['FORMAT']; ?>"<?= $data['SELECT']; ?>>
		<span class="custom-control-indicator"></span>
		<span class="custom-control-description"><?= $data['EXAMPLE']; ?></span>
	</label>
	<small class="form-text text-muted"><?= $data['FORMAT']; ?></small>
</p>
