<div class="row">
	<div class="column">
		
		<form class="ui form" method="post">
			<table class="ui definition table">
				<tbody>
					
					<tr>
						<td>
							<label for="language_title"><?= $this->l10n->gettext('title'); ?>:</label>
						</td>
						<td>
							<input type="text" id="language_title" name="language_title" value="<?= @$data['LANGUAGE_TITLE']; ?>">
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="language_parent"><?= $this->l10n->gettext('language_parent'); ?>:</label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" id="language_parent" name="language_parent">
								<option value="0"><?= $this->l10n->gettext('no_parent'); ?></option>
								<?= @$data['PARENT_LANGUAGES']; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="locale"><?= $this->l10n->gettext('locale'); ?>:</label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" id="locale" name="locale">
								<option><?= $this->l10n->gettext('select_locale'); ?></option>
								<?= @$data['LOCALES']; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td>
							<label><?= $this->l10n->gettext('text_direction'); ?>:</label>
						</td>
						<td>
							<div class="grouped fields">
								<div class="field">
									<div class="ui radio checkbox">
										<input id="text_lr" name="text_direction" type="radio" value="ltr" <?= ($data['TEXT_DIRECTION']=='ltr')?'checked':''; ?>>
										<label><?= $this->l10n->gettext('left_to_right'); ?></label>
									</div>
								</div>
								<div class="field">
									<div class="ui radio checkbox">
										<input id="text_rl" name="text_direction" type="radio" class="custom-control-input" value="rtl" <?= ($data['TEXT_DIRECTION']=='rtl')?'checked':''; ?>>
										<label><?= $this->l10n->gettext('right_to_left'); ?></label>
									</div>
								</div>
							</div>
						</td>
					</tr>
					
					<tr>
						<td>
							<label><?= $this->l10n->gettext('date_format'); ?>:</label>
						</td>
						<td>
							<div class="grouped fields">
								<?= $data['DATE_FORMATS']?>
								<div class="date_format" data-format-id="other">
									<div class="field">
										<div class="ui radio checkbox">
											<input name="date_format" id="other_dfs" type="radio" value="other">
											<label><?= $this->l10n->gettext('other'); ?></label>
										</div>
									</div>
									<div class="field">
										<input type="text" readonly data-id="other" id="other_date_format" value="">
										<label><?= $this->l10n->gettext('must_php_date_syntax'); ?></label>
									</div>
								</div>
							</div>
						</td>
					</tr>
					
					<tr>
						<td>
							<label><?= $this->l10n->gettext('time_format'); ?>:</label>
						</td>
						<td>
							<div class="grouped fields">
								<?= $data['TIME_FORMATS']?>
								<div class="time_format" data-format-id="other" >
									<div class="field">
										<div class="ui radio checkbox">
											<input name="time_format" id="other_tfs" type="radio" value="other">
											<label><?= $this->l10n->gettext('other'); ?></label>
										</div>
									</div>
									<div class="field">
										<input type="text" readonly data-id="other" id="other_time_format" value="">
										<label><?= $this->l10n->gettext('must_php_date_syntax'); ?></label>
									</div>
								</div>
							</div>
						</td>
					</tr>
					
				</tbody>
			</table>
			
			<button type="submit" class="ui huge primary fluid button"><?= $this->l10n->gettext('save'); ?></button>
			
		</form>
	</div>
</div>
