<tr>
	<td class="l10n-languages">
		<b><?php echo $data['TITLE']; ?></b>
		<span class="text-muted"><?php echo $data['LOCALE']; ?></span>
	</td>
	<td class="l10n-action">
		<a id="edit" href="<?php echo ADMIN_URL.'&do=l10n_languages&op=edit&language='.$data['ID']; ?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
		<a id="phrases" href="<?php echo ADMIN_URL.'&do=l10n_languages&op=phrases&language='.$data['ID']; ?>"><?php echo $this->l10n->gettext('phrases'); ?></a>
		<a id="delete" href="<?php echo ADMIN_URL.'&do=l10n_languages&op=delete&language='.$data['LOCALE']; ?>"><i class="fa fa-trash" aria-hidden="true"></i></a>

		<label class="custom-control custom-checkbox">
			<input type="checkbox" class="custom-control-input" name="language_id[]" value="<?php echo $data['LOCALE']; ?>">
			<span class="custom-control-indicator"></span>
		</label>
	</td>
</tr>