<tr>
	<td class="center aligned status"><i class="<?= $data['STATUS']; ?>"></i></td>
	<td>
		<a href="<?= BASE_URL; ?>?mode=<?= $data['NAME']; ?>" target="_blank"><i class="fa fa-share"></i></a> <?= $data['TITLE']; ?>
	</td>
	<td><?= $data['AUTHOR']; ?></td>
	<td><?= $data['VERSION']; ?></td>
	<td class="action">
		<div class="ui checkbox">
			<input type="checkbox" name="id[]" class="check-input" value="<?= $data['NAME']; ?>">
			<label></label>
		</div>
	</td>
</tr>