<div class="row">
	<div class="column">
		
		<form class="ui form panel-logs" method="post" action="<?= ADMIN_URL; ?>&do=logs&op=delete">
			
			<div class="ui fluid action input">
				<input type="text" id="adm-search-id" placeholder="<?= $this->l10n->gettext('search_placeholder'); ?>">
				<button class="ui basic button" data-for="#adm-search-id" type="button" rel="tooltip" title="<?= $this->l10n->gettext('search'); ?>">
					<i class="search fitted icon"></i>
				</button>
			</div>
			
			<table class="ui celled striped table">
				<thead>
					<tr>
						<th class="collapsing">
							<a href="#" class="sort-trigger" data-field="id" data-order="desc">#</a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="user" data-order="desc"><?= $this->l10n->gettext('logs_user'); ?></a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="msg" data-order="desc"><?= $this->l10n->gettext('action'); ?></a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="date" data-order="desc"><?= $this->l10n->gettext('date'); ?></a>
						</th>
					</tr>
				</thead>
				
				<tbody>
					<?= $data['LOGS']; ?>
				</tbody>
			</table>
			
			<div class="ui one column stackable center aligned page grid">
				<div class="column wide">
					<?= $data['PAGINATION']; ?>
				</div>
			</div>
			
		</form>
		
	</div>
</div>
