<form method="post" class="panel-logs" action="<?php echo ADMIN_URL; ?>&do=logs&op=delete">
	<div class="form-block">

		<div class="block-header">
			<div class="block-name">
				<p id="title">
					<span class="title"><?php echo $this->l10n->gettext('logs'); ?></span>
				</p>
				<p id="actions">
					<span class="btn-group" role="group">
						<input type="text" class="adm-search-input form-control" id="adm-search-id" placeholder="<?php echo $this->l10n->gettext('search_placeholder'); ?>">
						<span class="input-group-prepend">
							<button class="btn btn-secondary adm-search" data-for="#adm-search-id" type="button" rel="tooltip" title="<?php echo $this->l10n->gettext('search'); ?>"><i class="fa fa-search"></i></button>
						</span>
                    </span>
				</p>
			</div>
		</div>

		<?php if (!empty($data['PAGINATION'])) {?>
		<div class="block-line"></div>

		<div class="left-act"><?php echo $data['PAGINATION']; ?></div>
		<?php } ?>

		<div class="table-responsive">
			<table class="table table-striped table table-hover">
				<thead>
					<tr>
						<th><a href="#" class="sort-trigger" data-field="id" data-order="desc">#</a></th>
						<th><a href="#" class="sort-trigger" data-field="user" data-order="desc"><?php echo $this->l10n->gettext('logs_user'); ?></a></th>
						<th><a href="#" class="sort-trigger" data-field="msg" data-order="desc"><?php echo $this->l10n->gettext('action'); ?></a></th>
						<th><a href="#" class="sort-trigger" data-field="date" data-order="desc"><?php echo $this->l10n->gettext('date'); ?></a></th>
					</tr>
				</thead>

				<tbody>
					<?php echo $data['LOGS']; ?>
				</tbody>
			</table>
		</div>
	</div>
</form>