<tr>
	<td class="l10n-phrases">
		<b><?= $data['PHRASE']; ?></b> <span class="text-muted"><?= $data['PHRASE_VALUE']; ?></span>
	</td>
	<td class="l10n-action">
		<a id="edit" href="<?= ADMIN_URL.'&do=l10n_phrases&op=edit&language='.$data['LANGUAGE'].'&phrase='.$data['PHRASE']; ?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
		<a id="delete" href="<?= ADMIN_URL.'&do=l10n_phrases&op=delete&language='.$data['LANGUAGE'].'&phrase='.$data['PHRASE']; ?>"><i class="fa fa-trash" aria-hidden="true"></i></a>

		<div class="ui checkbox">
			<input type="checkbox" name="phrases_id[]" class="check-input" value="<?= $data['PHRASE']; ?>">
			<label></label>
		</div>

	</td>
</tr>
