<div class="form-block">

	<div class="block-header">
		<div class="block-name"><?= $data['PAGE']; ?></div>
	</div>

	<div class="block-line"></div>

	<form method="post">
		<h3><?= $data['TITLE']; ?></h3>
		<small>- <?= $data['DESC']; ?></small>
		<hr>
		<address>
			<dl>

				<dt><?= $this->l10n->gettext('author'); ?>:</dt>
				<dd><?= $data['AUTHOR']; ?></dd>

				<dt><?= $this->l10n->gettext('block_field_site'); ?>:</dt>
				<dd><a href="<?= $data['SITE']; ?>" target="_blank"><?= $data['SITE']; ?></a></dd>

				<dt><?= $this->l10n->gettext('block_field_email'); ?>:</dt>
				<dd><a href="mailto:<?= $data['EMAIL']; ?>"><?= $data['EMAIL']; ?></a></dd>

				<dt><?= $this->l10n->gettext('version'); ?>:</dt>
				<dd><?= $data['VERSION']; ?> <?= $data['UPDATE_RESULT']; ?></dd>
			</dl>
		</address>

		<div class="form-group">
			<label for="inputStatus"><?= $this->l10n->gettext('block_field_status'); ?></label>
			<select class="form-control" name="status" id="inputStatus">
				<option value="0"><?= $this->l10n->gettext('block_off'); ?></option>
				<option value="1"
				<?= $data['STATUS']; ?>><?= $this->l10n->gettext('block_on'); ?></option>
			</select>
		</div>

		<div class="form-group">
			<label for="inputUpdate"><?= $this->l10n->gettext('block_field_upd'); ?></label>
			<select class="form-control" name="updates" id="inputUpdate">
				<option value="0"><?= $this->l10n->gettext('block_off1'); ?></option>
				<option value="1"
				<?= $data['UPDATE_CHECK']; ?>><?= $this->l10n->gettext('block_on1'); ?></option>
			</select>
		</div>

		<div class="form-group">
			<label for="inputUrl"><?= $this->l10n->gettext('block_field_url'); ?></label>
			<input type="text" class="form-control" id="inputUrl" name="updater" value="<?= $data['UPDATE_URL']; ?>">
		</div>

		<div class="form-group">
			<label for="inputPos"><?= $this->l10n->gettext('block_field_pos'); ?></label>
			<input type="text" class="form-control" id="inputPos" name="position" value="<?= $data['POSITION']; ?>">
		</div>

		<button type="submit" class="btn btn-primary btn-block" name="submit"><?= $data['BUTTON']; ?></button>
	</form>

</div>