<tr>
	<td class="center aligned status"><i class="<?php echo $data['STATUS']; ?>"></i></td>
	<td><?php echo $data['TITLE']; ?></td>
	<td><?php echo $data['AUTHOR']; ?></td>
	<td><?php echo $data['VERSION']; ?></td>
	<td class="action">
		<div class="ui checkbox">
			<input type="checkbox" name="id[]" class="check-input" value="<?php echo $data['NAME']; ?>">
			<label></label>
		</div>
	</td>
</tr>