<div class="row">
	<div class="column">
		
		<h2 class="ui small header">
			<div class="content">
				<?= $data['PAGE']; ?> "<?= $data['TITLE']; ?>"
				<div class="sub header"><?= $data['DESC']; ?></div>
			</div>
		</h2>
		
		
		<form class="ui form" method="post">
			
			<div class="ui segment">
				
				<div class="ui horizontal list">
					<div class="item">
						<i class="user large icon"></i>
						<div class="content">
							<div class="header"><?= $this->l10n->gettext('author'); ?>:</div>
							<?= $data['AUTHOR']; ?>
						</div>
					</div>
					<div class="item">
						<i class="linkify large icon"></i>
						<div class="content">
							<div class="header"><?= $this->l10n->gettext('block_field_site'); ?>:</div>
							<a href="<?= $data['SITE']; ?>" target="_blank"><?= $data['SITE']; ?></a>
						</div>
					</div>
					<div class="item">
						<i class="at large icon"></i>
						<div class="content">
							<div class="header"><?= $this->l10n->gettext('block_field_email'); ?>:</div>
							<a href="mailto:<?= $data['EMAIL']; ?>"><?= $data['EMAIL']; ?></a>
						</div>
					</div>
					<div class="item">
						<i class="code branch large icon"></i>
						<div class="content">
							<div class="header"><?= $this->l10n->gettext('version'); ?>:</div>
							<?= $data['VERSION']; ?> <?= $data['UPDATE_RESULT']; ?>
						</div>
					</div>
				</div>
				
			</div>
			
			
			<table class="ui definition table">
				<tbody>
					<tr>
						<td><label for="inputStatus"><?= $this->l10n->gettext('block_field_status'); ?></label></td>
						<td>
							<select class="ui fluid selection dropdown" name="status" id="inputStatus">
								<option value="0"><?= $this->l10n->gettext('block_off'); ?></option>
								<option value="1"
								<?= $data['STATUS']; ?>><?= $this->l10n->gettext('block_on'); ?>
								</option>
							</select>
						</td>
					</tr>
					<tr>
						<td><label for="inputUpdate"><?= $this->l10n->gettext('block_field_upd'); ?></label></td>
						<td>
							<select class="ui fluid selection dropdown" name="updates" id="inputUpdate">
								<option value="0"><?= $this->l10n->gettext('block_off1'); ?></option>
								<option value="1"
								<?= $data['UPDATE_CHECK']; ?>><?= $this->l10n->gettext('block_on1'); ?>
								</option>
							</select>
						</td>
					</tr>
					<tr>
						<td><label for="inputUrl"><?= $this->l10n->gettext('block_field_url'); ?></label></td>
						<td>
							<input type="text" id="inputUrl" name="updater" value="<?= $data['UPDATE_URL']; ?>">
						</td>
					</tr>
					<tr>
						<td><label for="inputPos"><?= $this->l10n->gettext('block_field_pos'); ?></label></td>
						<td>
							<input type="number" id="inputPos" name="position" value="<?= $data['POSITION']; ?>">
						</td>
					</tr>
				</tbody>
			</table>
			
			<button type="submit" class="ui huge primary fluid button" name="submit"><?= $data['BUTTON']; ?></button>
		</form>
		
	</div>
</div>
