<div class="row">
	<div class="column">
		
		<form class="ui form menu-icon-change" method="post">
			
			<table class="ui definition table">
				<tbody>
					
					<tr>
						<td>
							<label for="inputTitle"><?= $this->l10n->gettext('mi_field_name'); ?></label>
						</td>
						<td>
							<input type="text" name="title" value="<?= $data['TITLE']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('mi_field_name'); ?>" required>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="inputImg"><?= $this->l10n->gettext('mi_field_img'); ?></label>
						</td>
						<td>
							<input type="text" name="img" value="<?= $data['IMG']; ?>" id="inputImg" placeholder="<?= $this->l10n->gettext('mi_field_img'); ?>">
						</td>
					</tr>
					
				</tbody>
			</table>
			
			<button type="submit" class="ui huge primary fluid button"><?= $data['BUTTON']; ?></button>
			
		</form>
		
	</div>
</div>
