<div class="form-block">
	<form method="post">
		<div class="form-group row">
			<label for="language" class="col-sm-4 col-form-label text-right"><?= $this->l10n->gettext('language'); ?></label>
			<div class="col-sm-6 float-left">
				<select class="form-control custom-select" id="language" name="language">
					<option disabled selected><?= $this->l10n->gettext('select_language'); ?></option>
					<?= $data['LANGUAGES']; ?>
				</select>
			</div>
		</div>

		<div class="form-group row">
			<label for="phrase" class="col-sm-4 col-form-label text-right"><?= $this->l10n->gettext('phrase'); ?></label>
			<div class="col-sm-6 float-left">
				<input type="text" class="form-control" id="phrase" name="phrase_key" value="<?= $data['PHRASE_KEY']; ?>">
				<small class="form-text text-muted">(<?= $this->l10n->gettext('must_be_unique'); ?>)</small>
			</div>
		</div>

		<div class="form-group row">
			<label for="value" class="col-sm-4 col-form-label text-right"><?= $this->l10n->gettext('phrase_value'); ?></label>
			<div class="col-sm-6 float-left">
				<textarea class="form-control" id="value" name="phrase_value" rows="5"><?= $data['PHRASE_VALUE']; ?></textarea>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-4 col-form-label text-right"></label>
			<div class="col-sm-6">
				<button type="submit" class="btn btn-success"><?= $this->l10n->gettext('save'); ?></button>
				<a href="<?= ADMIN_URL.'&do=l10n_phrases'; ?>" class="btn btn-outline-primary" role="button"><?= $this->l10n->gettext('cancel'); ?></a>
			</div>
		</div>
	</form>
</div>
