<div class="row">
	<div class="column">
		
		<form class="ui form" method="post">
			
			<table class="ui definition table">
				<tbody>
					<tr>
						<td><label for="language"><?= $this->l10n->gettext('language'); ?></label></td>
						<td>
							<select class="ui fluid selection dropdown" name="language" id="language">
								<option value="" disabled selected><?= $this->l10n->gettext('language_select'); ?></option>
								<?= $data['LANGUAGES']; ?>
							</select>
						</td>
					</tr>
					<tr>
						<td><label for="phrase"><?= $this->l10n->gettext('phrase'); ?></label></td>
						<td>
							<input type="text" class="form-control" id="phrase" name="phrase_key" value="<?= $data['PHRASE_KEY']; ?>">
							<small class="form-text text-muted"><?= $this->l10n->gettext('must_be_unique'); ?></small>
						</td>
					</tr>
					
					<tr>
						<td><label for="value"><?= $this->l10n->gettext('phrase_value'); ?></label></td>
						<td>
							<textarea id="value" name="phrase_value" rows="5"><?= $data['PHRASE_VALUE']; ?></textarea>
						</td>
					</tr>
					
				</tbody>
			</table>

			<button type="submit" class="ui huge primary fluid button"><?= $this->l10n->gettext('save'); ?></button>
		</form>
		
	</div>
</div>
