<script type="application/javascript" src="/themes/.application/js/datatables.min.js"></script>
<script type="application/javascript" src="/themes/.application/js/jquery.dataTables.min.js"></script>

<script type="application/javascript" src="/themes/.application/js/dataTables.semanticui.min.js"></script>

<script type="application/javascript" defer src="<?= asset('js/modules/l10n/phrases.js') ?>"></script>