<table id="phrases" class="ui table dataTable">
	<thead>
	<tr>
		<th class="l10n-phrases"><?= translate('phrases_list') ?></th>
		<th class="collapsing l10n-action sorting_disabled"><?= translate('action') ?></th>
	</tr>
	</thead>
	<tbody>
	</tbody>
    <tfoot>
    <tr>
        <th class="l10n-phrases"><?= translate('phrases_list') ?></th>
        <th class="collapsing l10n-action sorting_disabled"><?= translate('action') ?></th>
    </tr>
    </tfoot>
</table>