<tr>
	<td class="l10n-phrases">
		<b><?= $data['PHRASE']; ?></b> <span class="text-muted"><?= $data['PHRASE_VALUE']; ?></span>
	</td>
	<td class="l10n-action">
		<a id="edit" href="<?= ADMIN_URL.'&do=l10n_phrases&op=edit&language='.$data['LANGUAGE'].'&phrase='.$data['PHRASE']; ?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
		<a id="delete" href="<?= ADMIN_URL.'&do=l10n_phrases&op=delete&language='.$data['LANGUAGE'].'&phrase='.$data['PHRASE']; ?>"><i class="fa fa-trash" aria-hidden="true"></i></a>

		<label class="custom-control custom-checkbox">
			<input type="checkbox" class="custom-control-input" name="phrases_id[]" value="<?= $data['PHRASE']; ?>">
			<span class="custom-control-indicator"></span>
		</label>
	</td>
</tr>

