<div class="row">
	<div class="column">
		
		<form class="ui form" method="post" action="<?= ADMIN_URL.'&do=l10n_phrases&op=delete'; ?>">
			<input type="hidden" name="language" value="<?= (isset($_GET['language']))?$_GET['language']:0 ?>">
			
			<div class="block-header">
				<div class="block-name">
					<p id="title">
						<span class="title"></span>
						<small>
							<select id="to_language">
								<?= $data['LANGUAGES_LIST']?>
							</select>
							<?= $data['LANGUAGE_LOCALE']?>
						</small>
					</p>
				</div>
			</div>
			
			<table class="ui celled selectable table magic-datatables" id="phrases">
				<thead>
					<tr>
						<th class="l10n-phrases"><?= $this->l10n->gettext('phrases_list'); ?></th>
						<th class="collapsing l10n-action sorting_disabled"><?= $this->l10n->gettext('action'); ?></th>
					</tr>
				</thead>
				<tbody>
					<?= $data['PHRASES_LIST']?>
				</tbody>
			</table>
			
			<div id="actions" class="ui fluid buttons" role="group">
				<a class="ui primary button" role="button" href="<?= ADMIN_URL.'&do=l10n_phrases&op=export&language='.((isset($_GET['language']))?$_GET['language']:0); ?>"><?= $this->l10n->gettext('phrase_export'); ?></a>
				<a class="ui primary button" role="button" href="<?= ADMIN_URL.'&do=l10n_phrases&op=add'; ?>">
					<?= $this->l10n->gettext('phrase_add'); ?>
				</a>
				<button type="submit" class="ui negative button"><i class="icon trash" aria-hidden="true"></i></button>
			</div>
			
		</form>
		
	</div>
</div>
