<div class="form-block">

	<div class="block-header">
		<div class="block-name">
			<p id="title">
				<span class="title"><?php echo $data['PAGE']; ?></span>
			</p>
		</div>
	</div>

	<div class="block-line"></div>

	<form method="post">
		<div class="form-group row">
			<label for="inputCategory" class="col-sm-2 col-form-label"><?php echo $this->l10n->gettext('comment_col_news'); ?></label>
			<div class="col-sm-10">
				<select name="nid" type="text" class="form-control" id="inputCategory"><?php echo $data['NEWS']; ?></select>
			</div>
		</div>

		<div class="form-group row">
			<label for="inputText" class="col-sm-2 col-form-label"><?php echo $this->l10n->gettext('comment_col_comment'); ?></label>
			<div class="col-sm-10">
				<?php echo $data['BB_PANEL']; ?>
				<textarea id="inputText" placeholder="<?php echo $this->l10n->gettext('comment_text'); ?>" data-for="bb-comment" class="form-control" name="text" rows="6"><?php echo $data['TEXT']; ?></textarea>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<button type="submit" class="btn btn-primary" name="submit"><?php echo $data['BUTTON']; ?></button>
				<a role="button" class="btn btn-outline-secondary" href="<?php echo ADMIN_URL; ?>&do=comments"><?php echo $this->l10n->gettext('cancel'); ?></a>
			</div>
		</div>
	</form>
		
</div>