<div class="row">
	<div class="column">
		
		<form class="ui form menu-group-change" method="post">
			
			<table class="ui definition table">
				<tbody>
					
					<tr>
						<td>
							<label for="inputTitle"><?= $this->l10n->gettext('mgrp_field_name'); ?></label>
						</td>
						<td>
							<input type="text" name="title" value="<?= $data['TITLE']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('mgrp_field_name'); ?>" required>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="selectPerm"><?= $this->l10n->gettext('mgrp_field_access'); ?></label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" size="6" name="permissions" id="selectPerm">
								<?= $data['PERMISSIONS']; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="inputPriority"><?= $this->l10n->gettext('mgrp_field_priority'); ?></label>
						</td>
						<td>
							<input type="number" name="priority" value="<?= $data['PRIORITY']; ?>" pattern="^\d+$" id="inputPriority" placeholder="<?= $this->l10n->gettext('mgrp_field_priority'); ?>">
						</td>
					</tr>					
					
				</tbody>
			</table>
			
			<button type="submit" class="ui huge primary fluid button"><?= $data['BUTTON']; ?></button>
			
		</form>
		
	</div>
</div>
