<div class="form-block menu-group-change">

	<div class="block-header">
		<div class="block-name"><?= $data['PAGE']; ?></div>
	</div>

	<div class="block-line"></div>

	<form method="post">
		<div class="form-group">
			<label for="inputTitle"><?= $this->l10n->gettext('mgrp_field_name'); ?></label>
			<input type="text" class="form-control" name="title" value="<?= $data['TITLE']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('mgrp_field_name'); ?>" required>
		</div>

		<div class="form-group">
			<label for="textareaText"><?= $this->l10n->gettext('mgrp_field_desc'); ?></label>
			<textarea name="text" class="form-control" placeholder="<?= $this->l10n->gettext('mgrp_field_desc'); ?>" rows="8" maxlength="255" id="textareaText"><?= $data['TEXT']; ?></textarea>
		</div>

		<div class="form-group">
			<label for="selectPerm"><?= $this->l10n->gettext('mgrp_field_access'); ?></label>
			<select size="6" class="form-control" name="permissions" id="selectPerm">
				<?= $data['PERMISSIONS']; ?>
			</select>
		</div>

		<div class="form-group">
			<label for="inputPriority"><?= $this->l10n->gettext('mgrp_field_priority'); ?></label>
			<input type="text" class="form-control" name="priority" value="<?= $data['PRIORITY']; ?>" pattern="^\d+$" id="inputPriority" placeholder="<?= $this->l10n->gettext('mgrp_field_priority'); ?>">
		</div>

		<button type="submit" class="btn btn-primary btn-block" name="submit"><?= $data['BUTTON']; ?></button>
	</form>

</div>