<tr>
	<td><?= $data['ID']; ?></td>
	<td><i class="fa fa-info-circle" rel="tooltip" title="<?= $data['TEXT']; ?>"></i> <?= $data['TITLE']; ?>
	</td>
	<td><a href="#"><?= $data['PERMISSIONS']; ?></a> <!-- (Edit permissions link) Coming soon --></td>
	<td class="action">
		<div class="ui checkbox">
			<input type="checkbox" name="id[]" class="check-input" value="<?= $data['ID']; ?>">
			<label></label>
		</div>
	</td>
</tr>
