<div class="form-block menu-group-change">

	<div class="block-header">
		<div class="block-name"><?php echo $data['PAGE']; ?></div>
	</div>

	<div class="block-line"></div>

	<form method="post">
		<div class="form-group">
			<label for="inputTitle"><?php echo $this->l10n->gettext('mgrp_field_name'); ?></label>
			<input type="text" class="form-control" name="title" value="<?php echo $data['TITLE']; ?>" id="inputTitle" placeholder="<?php echo $this->l10n->gettext('mgrp_field_name'); ?>" required>
		</div>

		<div class="form-group">
			<label for="textareaText"><?php echo $this->l10n->gettext('mgrp_field_desc'); ?></label>
			<textarea name="text" class="form-control" placeholder="<?php echo $this->l10n->gettext('mgrp_field_desc'); ?>" rows="8" maxlength="255" id="textareaText"><?php echo $data['TEXT']; ?></textarea>
		</div>

		<div class="form-group">
			<label for="selectPerm"><?php echo $this->l10n->gettext('mgrp_field_access'); ?></label>
			<select size="6" class="form-control" name="permissions" id="selectPerm">
				<?php echo $data['PERMISSIONS']; ?>
			</select>
		</div>

		<div class="form-group">
			<label for="inputPriority"><?php echo $this->l10n->gettext('mgrp_field_priority'); ?></label>
			<input type="text" class="form-control" name="priority" value="<?php echo $data['PRIORITY']; ?>" pattern="^\d+$" id="inputPriority" placeholder="<?php echo $this->l10n->gettext('mgrp_field_priority'); ?>">
		</div>

		<button type="submit" class="btn btn-primary btn-block" name="submit"><?php echo $data['BUTTON']; ?></button>
	</form>

</div>