INSERT INTO `mcr_menu_adm_icons` (`title`, `img`)
VALUES
  ('По умолчанию', 'default.png'),
  ('Новости', 'news.png'),
  ('Пазл', 'puzzle.png'),
  ('Пользователь', 'user.png'),
  ('Пользователи', 'users.png'),
  ('Молоток и гаечный ключ', 'settings.png'),
  ('Древо', 'tree.png'),
  ('Диаграмма', 'diagram.png'),
  ('Лайк', 'like.png'),
  ('Документы', 'documents.png'),
  ('Иерархия', 'hierarchy.png'),
  ('Шестеренка', 'wheel.png'),
  ('Комментарии', 'comments.png'),
  ('Глаз', 'eye.png'),
  ('Группа пользователей', 'groups.png'),
  ('График', 'chart.png'),
  ('Замок', 'lock.png'),
  ('Блоки', 'blocks.png'),
  ('Иконка', 'icon.png'),
  ('Два листа', 'pages.png'),
  ('Монитор', 'monitor.png'),
  ('Сеть', 'network.png'),
  ('Открытая книга', 'logs.png'),
  ('Пустое древо', 'gealogy.png'),
  ('Языки', 'languages.png'),
  ('Фразы', 'phrases.png'),
  ('Модуль пользователей', 'us.png')
;