<link href="<?= STYLE_URL ?>css/owl.carousel.min.css" rel="stylesheet" media="screen">
<link href="<?= STYLE_URL ?>css/owl.theme.default.min.css" rel="stylesheet" media="screen">

<link href="<?= STYLE_URL ?>css/justifiedGallery.min.css" rel="stylesheet" media="screen">
<link href="<?= STYLE_URL ?>galery/css/lightgallery.min.css" rel="stylesheet" media="screen">
<!--<link href="--><?//=STYLE_URL?><!--css/morris.css" rel="stylesheet" media="screen">-->

<script src="<?= STYLE_URL ?>js/owl.carousel.min.js"></script>
<!--<script src="--><?//=STYLE_URL?><!--js/raphael.min.js"></script>-->
<!--<script src="--><?//=STYLE_URL?><!--js/morris.min.js"></script>-->
<!--<script src="--><?//=STYLE_URL?><!--js/highcharts/highcharts.js"></script>-->
<!--<script src="--><?//=STYLE_URL?><!--js/highcharts/modules/exporting.js"></script>-->
<!--<script src="--><?//=STYLE_URL?><!--js/highcharts/modules/export-data.js"></script>-->
<script src="<?= STYLE_URL ?>js/Chart.min.js"></script>

<script src="<?= STYLE_URL ?>js/jquery.justifiedGallery.min.js"></script>

<script src="<?= STYLE_URL ?>js/modules/admin/dashboard.js"></script>
