<form method="post" class="panel-votes" action="<?= ADMIN_URL; ?>&do=news_votes&op=delete">
	<div class="form-block">

		<div class="block-header">
			<div class="block-name">
				<p id="title">
					<span class="title"><?= $this->l10n->gettext('votes'); ?></span>
				</p>
				<p id="actions">
					<span class="btn-group">
						<button class="btn btn-secondary remove" data-for="check-input" data-text="<?= $this->l10n->gettext('remove_accept'); ?>" type="submit" name="delete"><i class="fa fa-times"></i></button>
					</span>
				</p>
			</div>
		</div>

		<? if (!empty($data['PAGINATION'])) {?>
		<div class="block-line"></div>

		<div class="left-act"><?= $data['PAGINATION']; ?></div>
		<? } ?>

		<div class="table-responsive">
			<table class="table table-striped table table-hover">
				<thead>
					<tr>
						<th><a href="#" class="sort-trigger" data-field="id" data-order="desc">#</a></th>
						<th>
							<a href="#" class="sort-trigger" data-field="news" data-order="desc"><?= $this->l10n->gettext('nvt_field_news'); ?></a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="value" data-order="desc"><?= $this->l10n->gettext('nvt_field_value'); ?></a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="user" data-order="desc"><?= $this->l10n->gettext('nvt_field_user'); ?></a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="date" data-order="desc"><?= $this->l10n->gettext('date'); ?></a>
						</th>
						<th class="action"><?= $this->l10n->gettext('action'); ?>
							<input type="checkbox" class="check-all" data-for="check-input"></th>
					</tr>
				</thead>

				<tbody>
					<?= $data['VOTES']; ?>
				</tbody>
			</table>
			</div>
	</div>
</form>
