<?php
$main = array (
  's_name' => 'MagicMCR',
  's_about' => 'Система управления сайтом',
  's_keywords' => 'Minecraft, webmcr, Magicmen, magicmcr, сервер, Qexy',
  's_dpage' => 'news',
  's_theme' => 'default',
  'rewrite' => false,
  'install' => true,
  'p_logic' => 'usual',
  'debug' => true,
  's_lang' => 'ru-RU',
  's_root' => '/',
  's_root_full' => 'http://192.168.0.128/',
  'mcr_secury' => 'dW8XC8CcrmE2RvOs7@r2',
  'crypt' => 0,
  'reg_accept' => true,
  'captcha' => 0,
  'rc_public' => '6LdNLf8SAAAAABs0jjSANg543acy6NGi4bH1MX-A',
  'rc_private' => '6LdNLf8SAAAAAO-XQUcGglTRw4ZZw2tO8163hudD',
  'kc_public' => '78758',
  'kc_private' => 'nBJjeiTqRAuXZlqwklPHSgtlCj',
  'skin_path' => 'uploads/skins/',
  'cloak_path' => 'uploads/cloaks/',
  'hd_cloaks' => false,
  's_client' => '',
);
?>