<div class="item">
	<form method="get" action="<?= BASE_URL; ?>">
		<input type="hidden" name="mode" value="search">
		<input type="hidden" name="type" id="search-hidden" value="news">
		
		<div class="ui action transparent input">
			<input type="text" name="value" placeholder="<?= $this->l10n->gettext('search'); ?>" required>
			<select class="ui compact selection dropdown">
				<?= $data['SEARCH_ELEMENTS']; ?>
			</select>
			<div class="ui button"><i class="icon search"></i></div>
		</div>
	</form>
</div>
