<div class="ui segments">

	<div class="ui segment">
		<?= $data['PAGE']; ?>
	</div>

	<div class="ui segment">
		<form class="ui form" method="post">
			<table class="ui definition table">
				<tbody>

					<tr>
						<td class="collapsing">
							<label for="inputTitle"><?= $this->l10n->gettext('mon_field_name'); ?></label>
						</td>
						<td>
							<input type="text" name="title" value="<?= $data['TITLE']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('mon_field_name'); ?>">
						</td>
					</tr>

					<tr>
						<td class="collapsing">
							<label for="inputText"><?= $this->l10n->gettext('mon_field_desc'); ?></label>
						</td>
						<td>
							<textarea id="inputText" placeholder="<?= $this->l10n->gettext('mon_field_desc'); ?>" name="text" maxlength="255" rows="5"><?= $data['TEXT']; ?></textarea>
						</td>
					</tr>

					<tr>
						<td class="collapsing">
							<label for="inputTitle"><?= $this->l10n->gettext('mon_field_ip'); ?></label>
						</td>
						<td>
							<input type="text" name="ip" value="<?= $data['IP']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('mon_field_ip'); ?>>">
						</td>
					</tr>

					<tr>
						<td class="collapsing">
							<label for="inputTitle"><?= $this->l10n->gettext('mon_field_port'); ?></label>
						</td>
						<td>
							<input type="number" name="port" value="<?= $data['PORT']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('mon_field_port'); ?>">
						</td>
					</tr>

					<tr>
						<td class="collapsing">
							<label for="inputType"><?= $this->l10n->gettext('mon_field_type'); ?></label>
						</td>
						<td>
							<select class="ui selection fluid dropdown" id="inputType" name="type">
								<?= $data['TYPES']; ?>
							</select>
						</td>
					</tr>

					<tr>
						<td class="collapsing">
							<label for="inputCache"><?= $this->l10n->gettext('mon_field_cache'); ?></label>
						</td>
						<td>
							<input type="number" name="cache" value="<?= $data['CACHE']; ?>" id="inputCache" placeholder="<?= $this->l10n->gettext('mon_field_cache'); ?>">
						</td>
					</tr>

					<tr>
						<td class="collapsing">
							<label for="inputError"><?= $this->l10n->gettext('mon_field_error'); ?></label>
						</td>
						<td>
							<input type="text" value="<?= $data['ERROR']; ?>" id="inputError" disabled placeholder="<?= $this->l10n->gettext('mon_field_error'); ?>">
						</td>
					</tr>

				</tbody>
			</table>
			<button type="submit" class="ui fluid primary button" name="submit"><?= $data['BUTTON']; ?></button>

		</form>
	</div>
</div>
