<p>
	<?= $this->l10n->gettext('register_email_1', $data['SITENAME']); ?> (<a href="<?= $data['SITEURL']; ?>" target="_blank" title="<?= $this->l10n->gettext('target_blank'); ?>"><?= $data['SITEURL']; ?></a>)
</p>
<?= $this->l10n->gettext('register_email_2', $data['LINK']); ?>
<br><br>
<p><?= $this->l10n->gettext('register_email_3'); ?> "<b><?= $data['SITENAME']; ?></b>" (<a href="<?= $data['SITEURL']; ?>" target="_blank" title="<?= $this->l10n->gettext('target_blank'); ?>"><?= $data['SITEURL']; ?></a>)
</p>