<div class="row">
	<div class="column">
		
		<form class="ui form" method="post">
			
			<table class="ui definition table">
				<tbody>
					
					<tr>
						<td>
							<label for="title"><?= $this->l10n->gettext('menu_field_name'); ?></label>
						</td>
						<td>
							<input type="text" name="title" value="<?= $data['TITLE']; ?>" id="title" placeholder="<?= $this->l10n->gettext('menu_field_name'); ?>">
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="url"><?= $this->l10n->gettext('menu_field_link'); ?></label>
						</td>
						<td>
							<input type="text" name="url" value="<?= $data['URL']; ?>" id="url" placeholder="<?= $this->l10n->gettext('menu_field_link'); ?>">
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="parent"><?= $this->l10n->gettext('menu_field_pos'); ?></label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" size="6" name="parent" id="parent">
								<?= $data['PARENTS']; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="target"><?= $this->l10n->gettext('menu_field_target'); ?></label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" size="6" name="target" id="target">
								<option value="_self" selected><?= $this->l10n->gettext('menu_target_self'); ?></option>
								<option value="_blank"<?= $data['TARGET']; ?>><?= $this->l10n->gettext('target_blank2'); ?></option>
							</select>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="permissions"><?= $this->l10n->gettext('menu_field_access'); ?></label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" size="6" name="permissions" id="permissions">
								<?= $data['PERMISSIONS']; ?>
							</select>
						</td>
					</tr>
					
				</tbody>
			</table>
			
			<button type="submit" class="ui huge primary fluid button"><?= $data['BUTTON']; ?></button>
			
		</form>
		
	</div>
</div>
