<div class="form-block">

	<div class="block-header">
		<div class="block-name">
			<p id="title">
				<span class="title"><?= $data['PAGE']; ?></span>
			</p>
		</div>
	</div>

	<div class="block-line"></div>

	<form method="post">
		<div class="form-group row">
			<label for="inputTitle" class="col-sm-2 col-form-label"><?= $this->l10n->gettext('menu_field_name'); ?></label>
			<div class="col-sm-10">
				<input type="text" class="form-control" name="title" value="<?= $data['TITLE']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('menu_field_name'); ?>">
			</div>
		</div>

		<div class="form-group row">
			<label for="inputUrl" class="col-sm-2 col-form-label"><?= $this->l10n->gettext('menu_field_link'); ?></label>
			<div class="col-sm-10">
				<input type="text" class="form-control" name="url" value="<?= $data['URL']; ?>" id="inputUrl" placeholder="<?= $this->l10n->gettext('menu_field_link'); ?>">
			</div>
		</div>

		<div class="form-group row">
			<label for="selectParent" class="col-sm-2 col-form-label"><?= $this->l10n->gettext('menu_field_pos'); ?></label>
			<div class="col-sm-10">
				<select size="6" class="form-control" name="parent" id="selectParent">
					<?= $data['PARENTS']; ?>
				</select>
			</div>
		</div>

		<!--<div class="form-group row">
			<label class="col-sm-2 col-form-label"><?= $this->l10n->gettext('menu_field_target'); ?></label>
			<div class="col-sm-10">
				<input type="radio" name="target[]" value="_self">
				<input type="radio" name="target[]" value="_blank">
			</div>
		</div>-->

		<div class="form-group row">
			<label for="selectTarget" class="col-sm-2 col-form-label"><?= $this->l10n->gettext('menu_field_target'); ?></label>
			<div class="col-sm-10">
				<select id="selectTarget" class="form-control" name="target">
					<option value="_self"><?= $this->l10n->gettext('menu_target_self'); ?></option>
					<option value="_blank"
					<?= $data['TARGET']; ?>><?= $this->l10n->gettext('target_blank2'); ?></option>
				</select>
			</div>
		</div>

		<div class="form-group row">
			<label for="selectPerm" class="col-sm-2 col-form-label"><?= $this->l10n->gettext('menu_field_access'); ?></label>
			<div class="col-sm-10">
				<select size="6" class="form-control" name="permissions" id="selectPerm">
					<?= $data['PERMISSIONS']; ?>
				</select>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<button type="submit" class="btn btn-primary" name="submit"><?= $data['BUTTON']; ?></button>
				<a role="button" class="btn btn-outline-secondary" href="<?= ADMIN_URL; ?>&do=menu"><?= $this->l10n->gettext('cancel'); ?></a>
			</div>
		</div>
	</form>

</div>