<form method="post" class="panel-menu" action="<?= ADMIN_URL; ?>&do=menu&op=delete">
	<div class="form-block">

		<div class="block-header">
			<div class="block-name">
				<p id="title">
					<span class="title"><?= $this->l10n->gettext('menu'); ?></span>
				</p>
				<p id="actions">
					<span class="btn-group">
						<a href="#" class="btn btn-secondary edit" data-for="check-input" data-link="<?= ADMIN_URL; ?>&do=menu&op=edit&id="><i class="fa fa-pencil"></i></a>
						<button class="btn btn-secondary remove" data-for="check-input" data-text="<?= $this->l10n->gettext('menu_accept'); ?>" type="submit" name="delete"><i class="fa fa-times"></i></button>
					</span>

					<span class="btn-group" role="group">
						<input type="text" class="adm-search-input form-control" id="adm-search-id" placeholder="<?= $this->l10n->gettext('search_placeholder'); ?>">
						<span class="input-group-prepend">
							<button class="btn btn-secondary adm-search" data-for="#adm-search-id" type="button" rel="tooltip" title="<?= $this->l10n->gettext('search'); ?>"><i class="fa fa-search"></i></button>
						</span>
                    </span>

					<span class="btn-group" role="group">
                    	<a role="button" href="<?= ADMIN_URL; ?>&do=menu&op=add" class="btn btn-primary"><?= $this->l10n->gettext('add'); ?></a>
                    </span>
				</p>
			</div>
		</div>

		<? if (!empty($data['PAGINATION'])) {?>
		<div class="block-line"></div>

		<div class="left-act"><?= $data['PAGINATION']; ?></div>
		<? } ?>

		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
					<tr>
						<th><a href="#" class="sort-trigger" data-field="id" data-order="desc">#</a></th>
						<th>
							<a href="#" class="sort-trigger" data-field="title" data-order="desc"><?= $this->l10n->gettext('menu_field_name'); ?></a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="parent" data-order="desc"><?= $this->l10n->gettext('menu_field_parent'); ?></a>
						</th>
						<th class="action"><?= $this->l10n->gettext('action'); ?>
							<input type="checkbox" class="check-all" data-for="check-input"></th>
					</tr>
				</thead>

				<tbody>
					<?= $data['MENU']; ?>
				</tbody>
			</table>
		</div>
	</div>
</form>