<div class="row">
	<div class="column">
		
		<form class="ui form panel-votes" method="post" action="<?= ADMIN_URL; ?>&do=news_votes&op=delete">
			
			<table class="ui celled striped table">
				<thead>
					<tr>
						<th class="collapsing">
							<a href="#" class="sort-trigger" data-field="id" data-order="desc">#</a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="news" data-order="desc"><?= $this->l10n->gettext('nvt_field_news'); ?></a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="value" data-order="desc"><?= $this->l10n->gettext('nvt_field_value'); ?></a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="user" data-order="desc"><?= $this->l10n->gettext('nvt_field_user'); ?></a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="date" data-order="desc"><?= $this->l10n->gettext('date'); ?></a>
						</th>
						<th class="collapsing action">
							<div class="ui checkbox">
								<input class="check-all" type="checkbox" data-for="check-input">
								<label></label>
							</div>
						</th>
					</tr>
				</thead>
				
				<tbody>
					<?= $data['VOTES']; ?>
				</tbody>
			</table>
			
			<div id="actions" class="field">
				<button class="ui fluid negative button remove" data-for="check-input" name="delete" type="submit">
					<i class="icon times"></i> <?= $this->l10n->gettext('delete'); ?>
				</button>
			</div>
			
			<div class="ui one column stackable center aligned page grid">
				<div class="column wide">
					<?= $data['PAGINATION']; ?>
				</div>
			</div>
			
		</form>
		
	</div>
</div>
