<div class="row">
	<div class="column">
		
		<form class="ui form panel-menu-adm" method="post" action="<?= ADMIN_URL; ?>&do=menu_adm&op=delete">
			
			<div class="ui fluid action input">
				<input type="text" id="adm-search-id" placeholder="<?= $this->l10n->gettext('search_placeholder'); ?>">
				<button class="ui basic button" type="button" data-for="#adm-search-id">
					<i class="search fitted icon"></i>
				</button>
			</div>
			
			<table class="ui celled striped table">
				<thead>
					<tr>
						<th class="collapsing"></th>
						<th>
							<a href="#" class="sort-trigger" data-field="title" data-order="desc"><?= $this->l10n->gettext('mcp_field_name'); ?></a>
						</th>
						<th>
							<a href="#" class="sort-trigger" data-field="group" data-order="desc"><?= $this->l10n->gettext('group'); ?></a>
						</th>
						<th class="collapsing action">
							<div class="ui checkbox">
								<input type="checkbox" class="check-all" data-for="check-input">
								<label></label>
							</div>
						</th>
					</tr>
				</thead>
				
				<tbody>
					<? foreach ($data['MENU'] as $pages) { ?>
						<tr>
							<td style="width: 3%;text-align: center">
								<input type="checkbox" id="fixed_<?= $pages['ID']; ?>" <?= $pages['FIXED']; ?> name="fixed" data-page="<?= $pages['ID']; ?>" class="check-input align-middle fixed_" value="1" style="display: none">
								<label for="fixed_<?= $pages['ID']; ?>" class="fa fa-paperclip paperclip"></label>
							</td>
							<td style="width: 20%;">
								<a href="<?= $pages['URL']; ?>" target="<?= $pages['TARGET']; ?>"><?= $pages['TITLE']; ?></a>
							</td>
							<td><?= $pages['GROUP']; ?></td>
							<td class="action">
								<div class="ui checkbox">
									<input type="checkbox" class="check-input" name="id[]" value="<?= $pages['ID']; ?>">
									<label></label>
								</div>
							</td>
						</tr>
					<? } ?>
				</tbody>
			</table>
			
			<!-- Admin links. Закладки. -->
			<!--
				<div class="card mt-4">
				<h5 class="card-header">Закладки</h5>
				<div class="card-body card-block">
				
				<h5 class="card-title block-name">
				Быстрые ссылки на необходимые ресурсы.
				</h5>
				<h6 class="card-subtitle mb-2 text-muted">Всегда под рукой.</h6>
				
				//
				</div>
				
				<ul class="list-group list-group-flush">
				<li class="list-group-item">Cras justo odio</li>
				<li class="list-group-item">Dapibus ac facilisis in</li>
				<li class="list-group-item">Vestibulum at eros</li>
				</ul>
			</div>-->
			
			<div class="field">
				<div id="actions" class="ui fluid buttons">
					<a class="ui primary button" href="<?= ADMIN_URL; ?>&do=menu_adm&op=add">
						<i class="icon plus"></i> <?= $this->l10n->gettext('add'); ?>
					</a>
					<a class="ui primary button edit" data-for="check-input" data-link="<?= ADMIN_URL; ?>&do=menu_adm&op=edit&id=">
						<i class="icon pencil"></i> <?= $this->l10n->gettext('edit'); ?>
					</a>
					<button class="ui negative button remove" data-for="check-input" name="delete" type="submit">
						<i class="icon times"></i> <?= $this->l10n->gettext('delete'); ?>
					</button>
				</div>
			</div>
			
			<? if (!empty($data['PAGINATION'])) {?>
				<div class="ui one column stackable center aligned page grid">
					<div class="column wide">
						<?= $data['PAGINATION']; ?>
					</div>
				</div>
			<? } ?>
			
		</form>
		
	</div>
</div>
