<p><?= $this->l10n->gettext('msg1'); ?></p>
<br>
<p><?= $this->l10n->gettext('msg2'); ?> "<b><?= $data['SITENAME']; ?></b>" (<a href="<?= $data['SITEURL']; ?>" target="_blank" title="<?= $this->l10n->gettext('target_blank'); ?>"><?= $data['SITEURL']; ?></a>)
</p>
<p><?= $this->l10n->gettext('msg3'); ?></p>
<p>
	<a href="<?= $data['LINK']; ?>" target="_blank" title="<?= $this->l10n->gettext('target_blank'); ?>"><?= $data['LINK']; ?></a>
</p>
<br>
<p><?= $this->l10n->gettext('msg4'); ?></p>
<br><br>
<p><?= $this->l10n->gettext('msg4'); ?> "<b><?= $data['SITENAME']; ?></b>" (<a href="<?= $data['SITEURL']; ?>" target="_blank" title="<?= $this->l10n->gettext('target_blank'); ?>"><?= $data['SITEURL']; ?></a>)
</p>