<div class="row">
	<div class="column">
		
		<div class="ui top attached tabular menu">
			<a class="item" href="<?= ADMIN_URL; ?>&do=info&op=main">
				<i class="list alternate icon"></i>
				<?= $this->l10n->gettext('system_log'); ?>
			</a>
			<a class="active item" href="<?= ADMIN_URL; ?>&do=info&op=update_center">
				<i class="sync alternate icon"></i>
				<?= $this->l10n->gettext('update_center'); ?>
			</a>
			<!--<a class="item" href="<?/*= ADMIN_URL; */?>&do=info&op=stats">
				<i class="chart bar icon"></i>
				<?/*= $this->l10n->gettext('info_stats'); */?>
			</a>-->
		</div>
		
		<div class="ui bottom attached active tab segment">

            <div class="ui items">
                <div class="item" id="update-info-panel" data-version="<?=VERSION?>" data-version-on-server="">
                    <div class="content">
                        <a class="header"><?=$this->l10n->gettext('update_state')?></a>
                        <div class="description">
                            <h2 class="ui header">
                                <i class="times circle red icon" id="update-status" style="display:none"></i>
                                <img src="/themes/semantic-ui/img/update.svg">
                                <div class="content" id="update-message">
                                    <?=$this->l10n->gettext('you_are_updated')?>
                                    <div class="sub header" style="display:block;font-size: 65%;line-height: 6px;" id="version-current"><?=VERSION?></div>
                                </div>
                            </h2>
                            <div style="padding-left: 76px">
								<?=$this->l10n->gettext('info_eng_ver_git')?>: <span id="version-on-server"></span><br>
                                <!--<?=$this->l10n->gettext('info_eng_ver_last')?>: <span id="version-stable"></span><br>-->
								<?=$this->l10n->gettext('info_eng_ver_dev')?>: <span id="version-dev"></span>
                            </div>
                        </div>
                        <div class="extra">
                            <a class="ui label" id="re-check">Проверить наличия обновлений</a>
                            <a class="ui label" href="/install/?do=reinstall"><i class="globe icon"></i> Переустановить MagicMCR</a>
                        </div>
                    </div>
                </div>
            </div>

		</div>
		
	</div>
</div>



