<div class="ui segments">

	<div class="ui segment"><?= $this->l10n->gettext('module_restore'); ?></div>

	<div class="ui segment mcr-restore">
		<form class="ui form" method="post">
			<div class="field">
				<label for="inputEmail"><?= $this->l10n->gettext('email'); ?></label>
				<input type="email" name="email" id="inputEmail" placeholder="<?= $this->l10n->gettext('email'); ?>" required>
			</div>

			<button type="submit" class="ui fluid primary huge button"><?= $this->l10n->gettext('restore'); ?></button>
		</form>
	</div>
</div>
