<div class="ui segments">

	<div class="ui segment"><?= $this->l10n->gettext('module_restore'); ?></div>

	<div class="ui segment mcr-restore">
		<form class="ui form" method="post">
			<div class="field">
				<label for="inputPass"><?= $this->l10n->gettext('new_pass'); ?></label>
				<input type="password" name="newpass" id="inputPass" placeholder="<?= $this->l10n->gettext('new_pass'); ?>" required>
			</div>

			<button type="submit" name="submit" class="ui fluid primary huge button"><?= $this->l10n->gettext('btn_edit'); ?></button>
		</form>
	</div>
</div>
