<div class="row">
	<div class="column">
		
		<form class="ui form form-horizontal" method="post">
			
			<table class="ui definition table">
				<tbody>
					
					<tr>
						<td class="collapsing">
							<label for="use_comments"><?= $this->l10n->gettext('use_comments'); ?></label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" id="use_comments" name="use_comments">
								<option value="0">Нет</option>
								<option value="1" <?= $data['USE_COMMENTS']; ?>>Да</option>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="users_on_page"><?= $this->l10n->gettext('users_on_page'); ?></label>
						</td>
						<td>
							<input type="number" min="5" id="users_on_page" name="users_on_page" value="<?= $data['CFG']['users_on_page']; ?>">
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="comments_on_page"><?= $this->l10n->gettext('comments_on_page'); ?></label>
						</td>
						<td>
							<input type="number" min="5" id="comments_on_page" name="comments_on_page" value="<?= $data['CFG']['comments_on_page']; ?>">
						</td>
					</tr>

				</tbody>
			</table>
			
			<button type="submit" name="submit" class="ui huge primary fluid button"><?= $this->l10n->gettext('save'); ?></button>
			
		</form>
		
	</div>
</div>
