<div class="ui segments">
 <div class="ui top attached tabular menu">
  <a class="active item" href="<?php echo ADMIN_URL; ?>&do=info&op=main">
   <?php echo $this->l10n->gettext('system_log'); ?>
  </a>
  <a class="item" href="<?php echo ADMIN_URL; ?>&do=info&op=update_center">
   <?php echo $this->l10n->gettext('update_center'); ?>
  </a>
  <a class="item" href="<?php echo ADMIN_URL; ?>&do=info&op=stats">
   <?php echo $this->l10n->gettext('info_stats'); ?>
  </a>
 </div>
 
 <div class="ui segment">
  
  <form method="post"></form>
  
  <div class="tab-content" id="log-viewer">
   <h5 id="log-title" class="text-muted"><?=$this->l10n->gettext('select_file');?></h5>
   <div class="ui grid">
    <div class="four wide column">
     <div class="ui vertical fluid menu" id="logs-list">
      
      <?php foreach($data['LOGS'] as $LOG) { ?>
       <a class="item" data-file-name="<?=$LOG?>"
       data-delete="<?php echo ADMIN_URL; ?>&do=info&op=delete" 
       data-download="<?php echo ADMIN_URL; ?>&do=info&op=download"
       data-archivate="<?php echo ADMIN_URL; ?>&do=info&op=archivate">
        <i class="fa fa-file-text"></i> <?=$LOG?>
       </a>
      <?php }?>
     </div>
    </div>
    <div class="twelve wide stretched column">
     <span id="update-file" class="update" title="<?=$this->l10n->gettext('update_file');?>"><i class="fa fa-refresh"></i></span>
     <pre id="log-content"></pre>
    </div>
   </div>
  
  </div>
  
 </div>
</div>
