<div class="ui top attached tabular menu">
	<a class="item" href="<?php echo ADMIN_URL; ?>&do=info&op=main">
		<?php echo $this->l10n->gettext('system_log'); ?>
	</a>
	<a class="item" href="<?php echo ADMIN_URL; ?>&do=info&op=update_center">
		<?php echo $this->l10n->gettext('update_center'); ?>
	</a>
	<a class="active item" href="<?php echo ADMIN_URL; ?>&do=info&op=stats">
		<?php echo $this->l10n->gettext('info_stats'); ?>
	</a>
</div>

<div class="ui bottom attached segment">
	<form method="post"></form>
	
	
	<table class="ui selectable celled table">
		<thead>
			<tr>
				<th colspan="2"><h3><?php echo $this->l10n->gettext('info_news_stats'); ?></h3></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><?php echo $this->l10n->gettext('info_count_news'); ?></td>
				<td class="text-right"><?php echo $data['COUNT_NEWS']; ?></td>
			</tr>
			
			<tr>
				<td><?php echo $this->l10n->gettext('info_count_views'); ?></td>
				<td class="text-right"><?php echo $data['COUNT_VIEWS']; ?></td>
			</tr>
			
			<tr>
				<td><?php echo $this->l10n->gettext('info_count_votes'); ?></td>
				<td class="text-right"><?php echo $data['COUNT_VOTES']; ?></td>
			</tr>
			
			<tr>
				<td><?php echo $this->l10n->gettext('info_count_cats'); ?></td>
				<td class="text-right"><?php echo $data['COUNT_CATEGORIES']; ?></td>
			</tr>
			
			<tr>
				<td><?php echo $this->l10n->gettext('info_count_coms'); ?></td>
				<td class="text-right"><?php echo $data['COUNT_COMMENTS']; ?></td>
			</tr>
		</tbody>
	</table>
	
	<table class="ui selectable celled table">
		<thead>
			<tr>
				<th colspan="2"><h3><?php echo $this->l10n->gettext('info_users_stats'); ?></h3></th>
			</tr>
		</thead>
		<tbody>
			<?php echo $data['USERS_STATS']; ?>
			
			<tr>
				<td><b><?php echo $this->l10n->gettext('info_count_users'); ?></b></td>
				<td class="text-right"><?php echo $data['COUNT_USERS']; ?></td>
			</tr>
			
			<tr>
				<td><b><?php echo $this->l10n->gettext('info_count_groups'); ?></b></td>
				<td class="text-right"><?php echo $data['COUNT_GROUPS']; ?></td>
			</tr>
		</tbody>
	</table>
	
	<table class="ui selectable celled table">
		<thead>
			<tr>
				<th colspan="2"><h3><?php echo $this->l10n->gettext('info_other'); ?></h3></th>
			</tr>
		</thead>
		<tbody>
			
			<tr>
				<td><?php echo $this->l10n->gettext('info_count_statics'); ?></td>
				<td class="text-right"><?php echo $data['COUNT_STATICS']; ?></td>
			</tr>
			
			<tr>
				<td><?php echo $this->l10n->gettext('info_count_perms'); ?></td>
				<td class="text-right"><?php echo $data['COUNT_PERMISSIONS']; ?></td>
			</tr>
			
		</tbody>
	</table>
</div>

