<div class="form-block">
	
	<div class="block-header"><?php echo $this->l10n->gettext('miniprofile'); ?></div>
	
	<div class="block-line"></div>
	
	<div class="block-content">
		<form class="block-profile" method="post" action="<?php echo BASE_URL; ?>?mode=logout">
			<div class="avatar"><img src="<?php echo SKIN_URL; ?>interface/<?php echo $this->user->skin; ?>_mini.png?<?php echo mt_rand(1000,9999); ?>" class="img-polaroid"></div>
			<ul class="info">
				<li><i class="fa fa-user"></i> <b><?php echo $this->l10n->gettext('login'); ?>:</b> <?php echo $this->user->login_v2; ?></li>
				<li><i class="fa fa-users"></i> <b><?php echo $this->l10n->gettext('group'); ?>:</b> <?php echo $this->user->group_v2; ?></li>
				<li><i class="fa fa-money"></i> <b><?php echo $this->l10n->gettext('balance'); ?>:</b> <?php echo $this->user->money; ?> <?php echo $this->l10n->gettext('cur_game'); ?></li>
				<li><a href="<?php echo BASE_URL; ?>?mode=profile" class="btn btn-secondary btn-block btn-sm"><?php echo $this->l10n->gettext('settings'); ?></a></li>
				<li><button type="submit" name="logout" value="1" class="btn btn-secondary btn-block btn-sm"><?php echo $this->l10n->gettext('logout'); ?></button></li>
			</ul>
		</form>
	</div>
	
</div>