<div class="ui top attached tabular menu">
	<a class="item" href="<?= ADMIN_URL; ?>&do=settings&op=main"><?= $this->l10n->gettext('set_main'); ?></a>
	<a class="item" href="<?= ADMIN_URL; ?>&do=settings&op=pagin"><?= $this->l10n->gettext('set_pagin'); ?></a>
	<a class="item" href="<?= ADMIN_URL; ?>&do=settings&op=mail"><?= $this->l10n->gettext('set_mail'); ?></a>
	<a class="item" href="<?= ADMIN_URL; ?>&do=settings&op=search"><?= $this->l10n->gettext('set_search'); ?></a>
	<a class="active item" href="<?= ADMIN_URL; ?>&do=settings&op=functions"><?= $this->l10n->gettext('set_func'); ?></a>
	<a class="item" href="<?= ADMIN_URL; ?>&do=settings&op=base"><?= $this->l10n->gettext('set_base'); ?></a>
</div>

<div class="ui bottom attached segment">
	<form method="post"></form>

	<div class="tab-content">
		<form class="ui form" method="post">
			<table class="ui definition table">
				<tbody>

					<tr>
						<td class="collapsing">
							<label for="input_advice"><?= $this->l10n->gettext('set_func_advice'); ?></label>
						</td>
						<td>
							<select name="advice" id="input_advice" class="ui fluid selection dropdown">
								<option value="0"><?= $this->l10n->gettext('no'); ?></option>
								<option value="1"
								<?= $data['ADVICE']; ?>><?= $this->l10n->gettext('yes'); ?></option>
							</select>
						</td>
					</tr>

					<tr>
						<td class="collapsing">
							<label for="input_breadcrumbs"><?= $this->l10n->gettext('set_funt_bc'); ?></label>
						</td>
						<td>
							<select name="breadcrumbs" id="input_breadcrumbs" class="ui fluid selection dropdown">
								<option value="0"><?= $this->l10n->gettext('no'); ?></option>
								<option value="1"
								<?= $data['BREADCRUMBS']; ?>><?= $this->l10n->gettext('yes'); ?></option>
							</select>
						</td>
					</tr>

					<tr>
						<td class="collapsing">
							<label for="input_close"><?= $this->l10n->gettext('set_funt_close'); ?></label>
						</td>
						<td>
							<select name="close" id="input_close" class="ui fluid selection dropdown">
								<option value="0"><?= $this->l10n->gettext('no'); ?></option>
								<option value="1"
								<?= $data['CLOSE']; ?>><?= $this->l10n->gettext('yes'); ?></option>
							</select>
						</td>
					</tr>

					<tr>
						<td class="collapsing">
							<label for="input_close_time"><?= $this->l10n->gettext('set_funt_close_time'); ?></label>
						</td>
						<td>
							<input type="text" name="close_time" id="input_close_time" value="<?= $data['CLOSE_TIME']; ?>">
						</td>
					</tr>

				</tbody>
			</table>

			<button type="submit" name="submit" class="ui huge primary fluid button"><?= $this->l10n->gettext('save'); ?></button>

		</form>
	</div>
</div>
