<div class="row">
	<div class="column">
		
		<form class="ui form menu-permissions-change" method="post">
			
			<table class="ui definition table">
				<tbody>
					
					<tr>
						<td class="collapsing">
							<label for="inputTitle"><?= $this->l10n->gettext('perm_field_name'); ?></label>
						</td>
						<td>
							<input type="text" name="title" value="<?= $data['TITLE']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('perm_field_name'); ?>" required>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="textareaText"><?= $this->l10n->gettext('perm_field_desc'); ?></label>
						</td>
						<td>
							<textarea name="text" placeholder="<?= $this->l10n->gettext('perm_field_desc'); ?>" rows="8" maxlength="255" id="textareaText"><?= $data['TEXT']; ?></textarea>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="inputPerm"><?= $this->l10n->gettext('perm_field_value'); ?></label>
						</td>
						<td>
							<input type="text" name="value" value="<?= $data['VALUE']; ?>" id="inputPerm" placeholder="<?= $this->l10n->gettext('perm_field_value'); ?>">
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="inputPerm"><?= $this->l10n->gettext('perm_field_type'); ?></label>
						</td>
						<td>
							<select class="ui fluid selection dropdown" name="type" id="perm-type">
								<?= $data['TYPES']; ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="inputDefault"><?= $this->l10n->gettext('perm_field_default'); ?></label>
						</td>
						<td>
							<div id="perm-default">
								<?= $data['DEFAULT']; ?>
							</div>
						</td>
					</tr>

				</tbody>
			</table>
			
			<button type="submit" class="ui huge fluid primary button" name="submit"><?= $data['BUTTON']; ?></button>
			
		</form>
		
	</div>
</div>
