<!DOCTYPE html>
<html lang="<?= explode('-', $this->l10n->get_config_locale())[0] ?>">
<head>
    <meta charset="utf-8">
	<title><?php echo $data['CFG']['s_name']; ?> — <?php echo $data['TITLE']; ?></title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<meta name="author" content="NC22 &amp; Qexy.org / completed Magicfar4 aka Magicmen">
	<meta name='data' content='<?php echo META_JSON_DATA; ?>'>

	<base href="<?php echo BASE_URL ?>">

	<?php echo $data['DEF_HEADER']; ?>

	<?php echo $data['HEADER']; ?>
</head>
<body>

    <div id="js-loader" title="<?php echo $this->l10n->gettext('loading'); ?>"><img src="<?php echo STYLE_URL; ?>img/ajaxload.info_FFFFFF_facebook.gif" alt="<?php echo $this->l10n->gettext('loading'); ?>"/></div>

	<section style="width:100%;height:100%;padding-top:24px;background:black" class="admin-wrapper">

		<aside>
            <div class="menu-header">
                <a href="/?mode=admin"><?=$this->l10n->gettext('module_admin-panel')?></a>
                <div class="sidebar-toggler fa fa-bars" onclick="$('html').toggleClass('sidebar-hide');"></div>
            </div>

            <ul class="nav-list" id="admin-menu">
				<?php echo $data["ADMIN_MENU"]; ?>
            </ul>
        </aside>

		<div class="admin-container form-block">

            <div class="breadcrumbs-container">
				<?php echo $data['BREADCRUMBS']; ?>
            </div>

			<?php echo $data['CONTENT']; ?>

            <div class="notifys">
                <div id="js-notify" class="alert alert-warning">
                    <a href="#" id="close">&times;</a>
                    <div id="title"></div>
                    <div id="message"></div>
                </div>

				<?php echo $data['L_BLOCKS']?>
            </div>

		</div>

	</section>

    <header style="display:flow-root;position:fixed;top:0;width:100%;">
        <div class="brand"><?=$this->cfg->main['s_name']?></div>

        <ul class="global-menu">
            <li class="nav-item"><a href="/" class="nav-link"><?=$this->l10n->gettext('home')?></a></li>

            <!--<li class="nav-item divider"></li>

            <li class="nav-item">
                <a href="/?mode=admin&do=info&op=update_center" class="nav-link icons" title="Обновлений нет" style="padding-right:1em">
                    <span class="fa fa-refresh nav-icon"></span>
                    <span class="badge ml-1">0</span>
                </a>
            </li>-->

            <?php $data['DEBUG'] = [
                "PLT" => number_format(microtime(true)-DEBUG_PLT,3),
                "QUERIES" => $this->db->count_queries,
                "MEMORY_USAGE" => intval(memory_get_usage()/1024),
                "MEMORY_PEAK" => intval(memory_get_peak_usage()/1024),
                "BASE_ERROR" => $this->db->error(),
                "PHP_ERROR" => error_get_last()
            ]; ?>

            <!-- START: Dev-tools -->
            <li class="nav-item divider"></li>

            <li class="nav-item">
                <a class="nav-link icons" title="<?=$this->l10n->gettext('debug_plt')?>: <?=$data['DEBUG']['PLT'] . ' ' . $this->l10n->gettext('sec')?>">
                    <i class="fa fa-tachometer" aria-hidden="true"></i>
                    <span class="badge ml-1"><?=$data['DEBUG']['PLT'] . ' ' . $this->l10n->gettext('sec')?></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link icons" title="<?=$this->l10n->gettext('debug_num_q')?>: <?=$data['DEBUG']['QUERIES']?>">
                    <i class="fa fa-database" aria-hidden="true"></i>
                    <span class="badge ml-1"><?=$data['DEBUG']['QUERIES']?></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link icons" title="<?=$this->l10n->gettext('system_errors')?>">
                    <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                    <span class="badge badge-default ml-1"><?=$this->log->get_logs_num('error')?></span>
                    <?php

                    if (!empty(error_get_last())) {
                        $error = error_get_last();
                        $type = $this->log->get_log_type($error['type']);
                        $error = "[{$type}] {$error['message']} in file: {$error['file']} on line: {$error['line']}";

                        ?>
                        <span class="badge badge-danger ml-1"
                              title="Last PHP error:"
                              data-container="body"
                              data-toggle="popover"
                              data-placement="bottom"
                              data-content="<?=$error?>"
                              style="cursor:pointer;"
                        >!</span>
                        <?php
                    }

                    ?>
                </a>
            </li>
            <!-- END: Dev-tools -->

            <li class="nav-item pull-right">
                <img width="20px" height="20px" src="<?=SKIN_URL?>interface/<?=$this->user->skin?>_mini.png?<?=mt_rand(1000,9999)?>">
                <a href="<?=BASE_URL.'?mode=profile'?>" class="nav-link"><?=$this->user->login?></a>
            </li>
        </ul>
    </header>

    <script src="<?=STYLE_URL?>galery/js/lightgallery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js"></script>

    <script src="<?=STYLE_URL?>galery/js/lg-thumbnail.min.js"></script>
    <script src="<?=STYLE_URL?>galery/js/lg-fullscreen.min.js"></script>
    <script src="<?=STYLE_URL?>galery/js/lg-pager.min.js"></script>
    <script src="<?=STYLE_URL?>galery/js/lg-zoom.min.js"></script>

</body>
</html>