<tr>
	<td><?= $data['ID']; ?></td>
	<td>
		<a href="<?= BASE_URL; ?>?mode=statics&id=<?= $data['UNIQ']; ?>" target="_blank"><i class="fa fa-share"></i></a> <?= $data['TITLE']; ?>
	</td>
	<td><?= $data['PERMISSIONS']; ?></td>
	<td class="right aligned action">
		<div class="ui checkbox">
			<input type="checkbox" name="id[]" class="check-input" value="<?= $data['ID']; ?>">
			<label></label>
		</div>
	</td>
</tr>
