<?php echo $data['PREVIEW']; ?>

<div class="form-block">
	<form method="post">
		<div class="form-group row">
			<label class="col-sm-4 col-form-label text-right" for="inputTitle"><?php echo $this->l10n->gettext('stc_field_name'); ?></label>
			<div class="col-sm-6 float-left">
				<input type="text" class="form-control" name="title" value="<?php echo $data['TITLE']; ?>" id="inputTitle" placeholder="<?php echo $this->l10n->gettext('stc_field_name'); ?>">
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-4 col-form-label text-right" for="inputUniq"><?php echo $this->l10n->gettext('stc_field_uniq'); ?></label>
			<div class="col-sm-6 float-left">
				<div class="input-group">
					<span class="input-group-addon"><?php echo $this->cfg->main['s_root_full']; ?>?mode=statics&id=</span>
					<input type="text" class="form-control" name="uniq" value="<?php echo $data['UNIQ']; ?>" id="inputUniq" placeholder="<?php echo $this->l10n->gettext('stc_field_uniq'); ?>">
				</div>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-4 col-form-label text-right" for="selectPerm"><?php echo $this->l10n->gettext('stc_field_access'); ?></label>
			<div class="col-sm-6 float-left">
				<select class="form-control" name="permissions" id="selectPerm">
					<?php echo $data['PERMISSIONS']; ?>
				</select>
			</div>
		</div>

		<div class="form-group row">
			<!--<label for="inputText"><?php echo $this->l10n->gettext('stc_field_text'); ?></label>-->
			<div class="col-md-12">
				<textarea class="tinymce bb-textarea" id="inputText" data-for="stc-field" placeholder="<?php echo $this->l10n->gettext('stc_field_text'); ?>" name="text" rows="30"><?php echo $data['TEXT']; ?></textarea>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-4 col-form-label text-right"></label>
			<div class="col-sm-6">
				<button type="submit" class="btn btn-primary" name="submit"><?php echo $data['BUTTON']; ?></button>
				<button type="submit" class="btn btn-secondary" name="preview"><?php echo $this->l10n->gettext('stc_field_preview'); ?></button>

				<a href="/?mode=admin&do=statics" class="btn btn-outline-secondary"><?php echo $this->l10n->gettext('cancel'); ?></a>
			</div>
		</div>
	</form>
</div>


<?php echo $this->file_manager(); ?>