<?= $data['PREVIEW']; ?>
<div class="row">
	<div class="column">
		
		<form class="ui form" method="post">
			
			<div class="field">
				<label for="inputTitle"><?= $this->l10n->gettext('stc_field_name'); ?></label>
				<input id="inputTitle" name="title" type="text"value="<?= $data['TITLE']; ?>" placeholder="<?= $this->l10n->gettext('stc_field_name'); ?>">
			</div>
			
			<div class="field">
				<label for="inputUniq"><?= $this->l10n->gettext('stc_field_uniq'); ?></label>
				<input id="inputUniq" name="uniq" type="text" value="<?= $data['UNIQ']; ?>" placeholder="<?= $this->l10n->gettext('stc_field_uniq'); ?>">
				<label><?= $this->cfg->main['s_root_full']; ?>?mode=statics&id=</label>
			</div>
			
			<div class="field">
				<label for="selectPerm"><?= $this->l10n->gettext('stc_field_access'); ?></label>
				<select class="ui fluid selection dropdown" name="permissions" id="selectPerm">
					<?= $data['PERMISSIONS']; ?>
				</select>
			</div>
			
			<div class="field">
				<label for="inputText"><?= $this->l10n->gettext('stc_field_text'); ?></label>
				<textarea class="tinymce bb-textarea" id="inputText" data-for="stc-field" placeholder="<?= $this->l10n->gettext('stc_field_text'); ?>" name="text" rows="30"><?= $data['TEXT']; ?></textarea>
			</div>
			
			<div class="field">
				<div class="ui fluid huge buttons">
					<button class="ui primary button" name="submit" type="submit"><?= $data['BUTTON']; ?></button>
					<button class="ui primary button" name="preview" type="submit"><?= $this->l10n->gettext('stc_field_preview'); ?></button>
				</div>
			</div>
			
		</form>
		
	</div>
</div>

<div class="row">
	<div class="column">
		<?= $this->file_manager(); ?>
	</div>
</div>
