<?= $data['PREVIEW']; ?>

<div class="form-block">
	<form method="post">
		<div class="form-group row">
			<label class="col-sm-4 col-form-label text-right" for="inputTitle"><?= $this->l10n->gettext('stc_field_name'); ?></label>
			<div class="col-sm-6 float-left">
				<input type="text" class="form-control" name="title" value="<?= $data['TITLE']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('stc_field_name'); ?>">
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-4 col-form-label text-right" for="inputUniq"><?= $this->l10n->gettext('stc_field_uniq'); ?></label>
			<div class="col-sm-6 float-left">
				<div class="input-group">
					<span class="input-group-addon"><?= $this->cfg->main['s_root_full']; ?>?mode=statics&id=</span>
					<input type="text" class="form-control" name="uniq" value="<?= $data['UNIQ']; ?>" id="inputUniq" placeholder="<?= $this->l10n->gettext('stc_field_uniq'); ?>">
				</div>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-4 col-form-label text-right" for="selectPerm"><?= $this->l10n->gettext('stc_field_access'); ?></label>
			<div class="col-sm-6 float-left">
				<select class="form-control" name="permissions" id="selectPerm">
					<?= $data['PERMISSIONS']; ?>
				</select>
			</div>
		</div>

		<div class="form-group row">
			<!--<label for="inputText"><?= $this->l10n->gettext('stc_field_text'); ?></label>-->
			<div class="col-md-12">
				<textarea class="tinymce bb-textarea" id="inputText" data-for="stc-field" placeholder="<?= $this->l10n->gettext('stc_field_text'); ?>" name="text" rows="30"><?= $data['TEXT']; ?></textarea>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-4 col-form-label text-right"></label>
			<div class="col-sm-6">
				<button type="submit" class="btn btn-primary" name="submit"><?= $data['BUTTON']; ?></button>
				<button type="submit" class="btn btn-secondary" name="preview"><?= $this->l10n->gettext('stc_field_preview'); ?></button>

				<a href="/?mode=admin&do=statics" class="btn btn-outline-secondary"><?= $this->l10n->gettext('cancel'); ?></a>
			</div>
		</div>
	</form>
</div>


<?= $this->file_manager(); ?>