<form method="post" class="panel-modules" action="<?php echo ADMIN_URL; ?>&do=modules&op=delete">
	<div class="form-block">

		<div class="block-header">
			<div class="block-name">
				<p id="title">
					<span class="title"><?php echo $this->l10n->gettext('modules'); ?></span>
				</p>
				<p id="actions">
					<span class="btn-group" role="group">
						<button class="btn btn-secondary" id="enable" data-for="check-input"><i class="fa fa-play"></i></button>
						<button class="btn btn-secondary" id="disable" data-for="check-input"><i class="fa fa-pause"></i></button>
                    </span>

					<span class="btn-group" role="group">
                    	<a role="button" href="#" class="btn btn-primary edit" data-for="check-input" data-link="<?php echo ADMIN_URL; ?>&do=modules&op=edit&id="><?php echo $this->l10n->gettext('edit'); ?></a>
                    </span>
				</p>
			</div>
		</div>

		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
					<tr>
						<th><?php echo $this->l10n->gettext('mod_field_status'); ?></th>
						<th><?php echo $this->l10n->gettext('mod_field_name'); ?></th>
						<th><?php echo $this->l10n->gettext('author'); ?></th>
						<th><?php echo $this->l10n->gettext('version'); ?></th>
						<th class="action"><?php echo $this->l10n->gettext('action'); ?> <input type="checkbox" class="check-all" data-for="check-input"></th>
					</tr>
				</thead>

				<tbody>
					<?php echo $data['MODULES']; ?>
				</tbody>
			</table>
		</div>
	</div>
</form>