<p>
	<?php echo $this->l10n->gettext('register_email_1', $data['SITENAME']); ?> (<a href="<?php echo $data['SITEURL']; ?>" target="_blank" title="<?php echo $this->l10n->gettext('target_blank'); ?>"><?php echo $data['SITEURL']; ?></a>)
</p>
<?php echo $this->l10n->gettext('register_email_2', $data['LINK']); ?>
<br><br>
<p><?php echo $this->l10n->gettext('register_email_3'); ?> "<b><?php echo $data['SITENAME']; ?></b>" (<a href="<?php echo $data['SITEURL']; ?>" target="_blank" title="<?php echo $this->l10n->gettext('target_blank'); ?>"><?php echo $data['SITEURL']; ?></a>)</p>