<!--
Copyright (c) 2018.
MagicMCR является отдельным и независимым продуктом.
Исходный код распространяется под лицензией GNU General Public License v3.0.

MagicMCR не является копией оригинального движка WebMCR, а лишь его подверсией.
Разработка MagicMCR производится исключительно в частных интересах. Разработчики, а также лица,
участвующие в разработке и поддержке, не несут ответственности за проблемы, возникшие с движком.
-->
<!DOCTYPE HTML>
<?= document('open') ?>
	<head>
        <meta charset="utf-8">
		<title><?= $title ?> — <?= config('mcr::site.name') ?></title>

		<meta name="viewport" content="width=device-width, initial-scale=1.0">

        <meta name="description" content="<?= config('mcr::site.description') ?>">
        <meta name="keywords" content="<?= config('mcr::site.keywords') ?>">
        <meta name="author" content="NC22 &amp; Qexy.org / completed Magicfar4 aka Magicmen">

        <meta name='application' content='<?= META_JSON_DATA ?>'>

        <base href="<?= BASE_URL ?>">

        <!-- Base stylesheets -->
        <link rel="stylesheet" href="/themes/.semantic/dist/semantic.min.css">
        <link rel="stylesheet" href="<?= asset('css/jquery.minicolors.css') ?>">
        <link rel="stylesheet" href="<?= asset('css/global.css') ?>">

        <!-- User stylesheets -->
		<?php stylesheets(); ?>

        <!-- Head scripts -->
        <script type="application/javascript" src="<?= asset('js/jquery.min.js') ?>"></script>
		<?php scripts('head'); ?>
	</head>

	<?= document('open_body') ?>

        <?php $_menu = menu()->generate(); ?>

		<!-- Sidebar Menu -->
		<div class="ui vertical inverted sidebar menu">
			<?= $_menu ?>
		</div>

		<div id="mcr-header" class="ui vertical masthead segment">
            <div class="ui top fixed menu">
                <div class="ui container">
                    <a class="hidden-menu toc item">
                        <i class="sidebar icon"></i>
                    </a>
	                <?= $_menu ?>
                    <div class="right menu">
                        <!-- TODO: Search -->
                    </div>
                </div>
            </div>

			<div class="ui text container">
				<img id="mcr-logotype" class="ui right floated image" src="<?= asset('img/logotype.png') ?>">
				<div class="ui header">
					<h1><?= config('mcr::site.name') ?></h1>
					<div class="ui sub header">
						<p><?= config('mcr::site.description') ?></p>
						<p>
							<a class="ui huge green button" href="index.php?mode=start" role="button"><i class="icon download"></i> <?= translate('load_client'); ?></a>
						</p>
					</div>
				</div>
			</div>

		</div>

		<div class="ui vertical segment" id="mcr-content-container">

			<?= $advice ?>

			<div class="ui stackable relaxed mobile reversed grid container">
                <!-- Left side -->
				<div class="four wide left floated column" id="mcr-sidebar">

					<?php blocks()->render(['block_banner', 'block_monitoring', 'block_online', 'block_profile']); ?>

				</div>

				<!-- Right side -->
				<div class="twelve wide right floated column" id="mcr-content">

					<?php
					echo $breadcrumbs;

					echo $content;
					?>

				</div>

			</div>

		</div>


		<div id="js-loader" title="<?= translate('loading'); ?>">
			<img src="<?= asset('img/ajaxload.gif') ?>" alt="<?= translate('loading') ?>"/>
		</div>

		<div id="mcr-footer">
			<div class="feature alternate ui stripe vertical segment">
				<div class="ui container">
					<h4 class="ui inverted header"><?= sprintf(translate('copyright'), config('mcr::site.name')); ?></h4>
					<p><?= FEEDBACK ?> | <?= VERSION ?></p>
				</div>
			</div>
		</div>

        <div class="ui messages">
            <div class="ui black async message">
                <i class="close icon"></i>
                <div id="title" class="header"></div>
                <p id="message"></p>
            </div>

            <?php blocks()->render('block_notify') ?>
        </div>

        <!-- Base body scripts -->
        <script type="application/javascript" src="<?= asset('js/jquery.easing.js') ?>"></script>
        <script type="application/javascript" src="/themes/.semantic/dist/semantic.min.js"></script>
        <script type="application/javascript" src="<?= asset('js/bootstrap.file-input.js') ?>"></script>
        <script type="application/javascript" src="<?= asset('js/jquery.minicolors.min.js') ?>"></script>
        <script type="application/javascript" src="<?= asset('js/cookie.js') ?>"></script>
        <script type="application/javascript" src="/themes/.application/application.js"></script>
        <script type="application/javascript" src="<?= asset('js/global.js') ?>"></script>

        <!-- User body scripts -->
        <?php scripts('body'); ?>

    <?= document('close', ['body']) ?>

<?= document('close') ?>
