<?php
use mcr\l10n\l10n;
?>

<!DOCTYPE HTML>
<html lang="<?= explode('-', l10n::get_config_locale())[0] ?>">
<head>
    <meta charset="utf-8">
	<title><?= config('main::s_name') ?> — <?= $title ?></title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<meta name="description" content="<?= config('main::s_about') ?>">
	<meta name="keywords" content="<?= config('main::s_keywords') ?>">
	<meta name="author" content="NC22 &amp; Qexy.org / completed Magicfar4 aka Magicmen">

	<meta name='data' content='<?= META_JSON_DATA; ?>'>

	<base href="<?= BASE_URL ?>">

    <?php
    // Добавление стилей в регистр
    stylesheet([
        asset('css/global.css'),
		asset('css/font-awesome.min.css'),
		asset('css/bootstrap.min.css'),
		asset('css/jquery.minicolors.css'),
    ], true);

    // Подключаем стили
    stylesheets();
    // Подключае скрипты, которые требуют своего расположение в head
	scripts('head');
    ?>

</head>

<body style="direction:<?= l10n::get_locale_info('text_direction') ?>;" class="global">

    <nav class="navbar navbar-toggleable-md navbar-light bg-faded fixed-top">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <a class="navbar-brand mb-0 h1" href="<?= BASE_URL; ?>"><?= config('main::s_name') ?></a>

            <div class="collapse navbar-collapse" id="navbar-header">
                <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                    <?php echo menu()->generate(); ?>
                </ul>
                <?= $search ?>
            </div>
        </div>

        <div class="bg"></div>
    </nav>

    <header class="jumbotron jumbotron-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <h1 class="display-3"><?= config('main::s_name') ?></h1>
                    <p><?= config('main::s_about') ?></p>
                    <p><a class="btn btn-success btn-lg" href="index.php?mode=start" role="button">
                            <i class="fa fa-download"></i> <?= translate('load_client') ?>
                        </a>
                    </p>
                </div>

                <div class="col-md-4">
                    <img src="/themes/default/img/logotype.png">
                </div>
            </div>
        </div>
    </header>

    <?= $advice ?>

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div id="js-notify" class="alert alert-warning">
                    <a href="#" id="close">&times;</a>
                    <div id="title"></div>
                    <div id="message"></div>
                </div>

                <?= $blocks ?>
            </div>

            <div class="col-md-8">
                <?= $breadcrumbs ?>

                <?= $content ?>
            </div>
        </div>
    </div>

    <div id="js-loader" title="<?= translate('loading'); ?>"><img src="<?= asset('img/ajaxload.info_FFFFFF_facebook.gif') ?>" alt="<?= translate('loading'); ?>"/></div>

    <nav class="navbar navbar-light bg-faded">
        <div class="container">
            <div id="navbar-footer">
                <div class="block-left"><?php echo sprintf(translate('copyright'), config('main::s_name')) ?></div>
                <div class="block-right" style="white-space: nowrap"><?php echo FEEDBACK; ?> | <?php echo VERSION; ?></div>
            </div>
        </div>
    </nav>

	<?php
    // Добавляем скрипты в регистр
    script('body', asset('js/jquery.min.js'));
    script('body', asset('js/jquery.easing.js'));
    script('body', asset('js/popper.min.js'));
    script('body', asset('js/tether.min.js'));
    script('body', asset('js/bootstrap.min.js'));
    script('body', asset('js/bootstrap.file-input.js'));
    script('body', asset('js/jquery.minicolors.min.js'));
    script('body', LANG_URL . 'js/global.js');
    script('body', asset('js/cookie.js'));
    script('body', asset('js/global.js'));

    // Подключаем скрипты, которые требуют своего расположение перед закрывающим тегом body.
    scripts('body');
    ?>

</body>

</html>