<?php
use mcr\l10n\l10n;
?>

<!DOCTYPE HTML>
<html lang="<?= explode('-', l10n::get_config_locale())[0] ?>">
<head>
    <meta charset="utf-8">
	<title><?= $title ?> — <?= config('main::s_name') ?></title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<meta name="description" content="<?= config('main::s_about') ?>">
	<meta name="keywords" content="<?= config('main::s_keywords') ?>">
	<meta name="author" content="NC22 &amp; Qexy.org / completed Magicfar4 aka Magicmen">

	<meta name='data' content='<?= META_JSON_DATA; ?>'>

	<base href="<?= BASE_URL ?>">

    <!-- Base stylesheets -->
    <link rel="stylesheet" href="<?= asset('css/font-awesome.min.css') ?>">
    <link rel="stylesheet" href="<?= asset('css/bootstrap.min.css') ?>">
    <link rel="stylesheet" href="<?= asset('css/jquery.minicolors.css') ?>">
    <link rel="stylesheet" href="<?= asset('css/global.css') ?>">

    <!-- User stylesheets -->
    <?php stylesheets(); ?>

    <!-- Head scripts -->
    <script type="application/javascript" src="<?= asset('js/jquery.min.js') ?>"></script>
    <?php scripts('head'); ?>

</head>

<body style="direction:<?= l10n::get_locale_info('text_direction') ?>;" class="global">

    <nav class="navbar navbar-toggleable-md navbar-light bg-faded fixed-top">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <a class="navbar-brand mb-0 h1" href="<?= BASE_URL; ?>"><?= config('main::s_name') ?></a>

            <div class="collapse navbar-collapse" id="navbar-header">
                <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                    <?php echo menu()->generate(); ?>
                </ul>
            </div>
        </div>

        <div class="bg"></div>
    </nav>

    <header class="jumbotron jumbotron-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <h1 class="display-3"><?= config('main::s_name') ?></h1>
                    <p><?= config('main::s_about') ?></p>
                    <p><a class="btn btn-success btn-lg" href="index.php?mode=start" role="button">
                            <i class="fa fa-download"></i> <?= translate('load_client') ?>
                        </a>
                    </p>
                </div>

                <div class="col-md-4">
                    <img src="/themes/default/img/logotype.png">
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div id="js-notify" class="alert alert-warning">
                    <a href="#" id="close">&times;</a>
                    <div id="title"></div>
                    <div id="message"></div>
                </div>

                <?php blocks()->render(); ?>
            </div>

            <div class="col-md-8">
                <?= $content ?>
            </div>
        </div>
    </div>

    <div id="js-loader" title="<?= translate('loading'); ?>"><img src="<?= asset('img/ajaxload.info_FFFFFF_facebook.gif') ?>" alt="<?= translate('loading'); ?>"/></div>

    <nav class="navbar navbar-light bg-faded">
        <div class="container">
            <div id="navbar-footer">
                <div class="block-left"><?php echo sprintf(translate('copyright'), config('main::s_name')) ?></div>
                <div class="block-right" style="white-space: nowrap"><?php echo FEEDBACK; ?> | <?php echo VERSION; ?></div>
            </div>
        </div>
    </nav>

    <!-- Base body scripts -->
    <script type="application/javascript" src="<?= asset('js/jquery.easing.js') ?>"></script>
    <script type="application/javascript" src="<?= asset('js/popper.min.js') ?>"></script>
    <script type="application/javascript" src="<?= asset('js/tether.min.js') ?>"></script>
    <script type="application/javascript" src="<?= asset('js/bootstrap.min.js') ?>"></script>
    <script type="application/javascript" src="<?= asset('js/bootstrap.file-input.js') ?>"></script>
    <script type="application/javascript" src="<?= asset('js/jquery.minicolors.min.js') ?>"></script>
    <script type="application/javascript" src="<?= LANG_URL . 'js/global.js' ?>"></script>
    <script type="application/javascript" src="<?= asset('js/cookie.js') ?>"></script>
    <script type="application/javascript" src="<?= asset('js/global.js') ?>"></script>

    <!-- User body scripts -->
	<?php scripts('body'); ?>

</body>

</html>