<link href="<?= STYLE_URL; ?>css/global.css" rel="stylesheet" media="screen">
<link href="<?= STYLE_URL; ?>css/semantic.min.css" rel="stylesheet">
<link href="<?= STYLE_URL; ?>css/jquery.minicolors.css" rel="stylesheet" media="screen">
<script src="<?= STYLE_URL; ?>js/jquery.min.js"></script>
<script src="<?= STYLE_URL; ?>js/jquery.easing.js"></script>
<script src="<?= STYLE_URL; ?>js/semantic.min.js"></script>
<script src="<?= STYLE_URL; ?>js/bootstrap.file-input.js"></script>
<script src="<?= STYLE_URL; ?>js/jquery.minicolors.min.js"></script>
<script src="<?= LANG_URL; ?>js/global.js"></script>
<script src="<?= STYLE_URL; ?>js/cookie.js"></script>
<script src="<?= STYLE_URL; ?>js/global.js"></script>
