<div class="form-block">

	<div class="block-header">
		<div class="block-name">
			<p id="title">
				<span class="title"><?= $data['PAGE']; ?></span>
			</p>
		</div>
	</div>

	<div class="block-line"></div>

	<form method="post">
		<div class="form-group row">
			<label class="col-sm-2 col-form-label" for="inputTitle"><?= $this->l10n->gettext('grp_field_name'); ?></label>
			<div class="col-sm-10">
				<input type="text" class="form-control" name="title" value="<?= $data['TITLE']; ?>" id="inputTitle" placeholder="<?= $this->l10n->gettext('grp_field_name'); ?>" required>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-label" for="inputColor">Цвет группы</label>
			<div class="col-sm-10">
				<input type="text" name="color" class="form-control" value="<?= $data['COLOR']; ?>" placeholder="#000000 | #000" id="inputColor">
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-label" for="textareaText"><?= $this->l10n->gettext('grp_field_desc'); ?></label>
			<div class="col-sm-10">
				<textarea name="text" class="form-control" placeholder="<?= $this->l10n->gettext('grp_field_desc'); ?>" rows="8" maxlength="255" id="textareaText"><?= $data['TEXT']; ?></textarea>
			</div>
		</div>

		<div id="permissions-container">
			<table id="permissions" class="table table-striped table-sm hide">
				<tbody>
					<?= $data['PERMISSIONS']; ?>
				</tbody>
			</table>

			<span><?= $this->l10n->gettext('grp_field_perm'); ?> <i class="fa"></i></span>
		</div>

		<div class="form-group row">
			<label class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<button type="submit" class="btn btn-primary" name="submit"><?= $data['BUTTON']; ?></button>
				<a role="button" class="btn btn-outline-secondary" href="<?= ADMIN_URL; ?>&do=groups"><?= $this->l10n->gettext('cancel'); ?></a>
			</div>
		</div>
	</form>

</div>
