<div class="row">
	<div class="column">
		
		<form class="ui form" method="post">
			
			<table class="ui definition table">
				<tbody>
					
					<tr>
						<td class="collapsing">
							<label for="inputTitle"><?= $this->l10n->gettext('grp_field_name'); ?></label>
						</td>
						<td>
							<input id="inputTitle" name="title" type="text" value="<?= $data['TITLE']; ?>" placeholder="<?= $this->l10n->gettext('grp_field_name'); ?>" required>
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="inputTitle">Цвет группы</label>
						</td>
						<td>
							<input type="text" name="color" value="<?= $data['COLOR']; ?>" placeholder="#000000 | #000" id="inputColor">
						</td>
					</tr>
					
					<tr>
						<td class="collapsing">
							<label for="textareaText"><?= $this->l10n->gettext('grp_field_desc'); ?></label>
						</td>
						<td>
							<textarea name="text" placeholder="<?= $this->l10n->gettext('grp_field_desc'); ?>" rows="8" maxlength="255" id="textareaText"><?= $data['TEXT']; ?></textarea>
						</td>
					</tr>
					
				</tbody>
			</table>
			
			<div id="permissions-container">
				<table id="permissions" class="ui striped table table-sm hide">
					<tbody>
						<?= $data['PERMISSIONS']; ?>
					</tbody>
				</table>
				
				<span><?= $this->l10n->gettext('grp_field_perm'); ?> <i class="fa"></i></span>
			</div>
			
			<button type="submit" class="ui huge fluid primary button" name="submit"><?= $data['BUTTON']; ?></button>
			
		</form>
		
	</div>
</div>
