<tr>
	<td class="news-id"><?= $data['ID']; ?></td>
	<td class="news-title">
		<div id="left">
			<p id="img">
				<img src="<?= $data['IMG']; ?>" class="img-polaroid img-thumbnail" alt="<?= str_replace(' ', '_', $data['TITLE']).'.'.$data['ID']; ?>" width="32px">
				<?= $data['USER_AVATARS']; ?>
			</p>
		</div>
		<div id="right">
			<div class="top">
				<p id="title"><a href="<?= BASE_URL; ?>?mode=news&id=<?= $data['ID']; ?>" target="_blank">
					<b><?= $data['TITLE']; ?></b> <i class="fa fa-share"></i>
				</a></p>
				
				<p id="information" style="padding-right: 10px;" class="float-right text-right"><?= $data['INFORMATION']?></p>
			</div>
			
			<div class="bottom text-muted">
				<p id="author"><?= $data['AUTHORS']; ?></p>
				
				<span id="date" class="float-right"><?= $data['DATE']; ?></span>
			</div>
		</div>
	</td>
	<td class="news-category">
		<div class="top">
			<a href="<?= BASE_URL; ?>?mode=news&cid=<?= $data['CID']; ?>" target="_blank">
				<?= $data['CATEGORY']; ?> <i class="fa fa-share"></i>
			</a>
		</div>
		
		<div class="bottom text-muted" data-toggle="tooltip" data-placement="left" title="<?= $data['DESCRIPTION']; ?>">
			<p><?= $data['DESCRIPTION']; ?></p>
		</div>
	</td>
	<td class="right aligned news-action">

		<div class="ui checkbox">
			<input type="checkbox" name="news_id[]" value="<?= $data['ID']; ?>">
			<label></label>
		</div>
		
	</td>
</tr>
