<link href="<?php echo STYLE_URL; ?>css/modules/news/news-full.css" rel="stylesheet" media="screen">
<script src="<?php echo LANG_URL; ?>js/modules/news-full.js"></script>
<script src="<?php echo STYLE_URL; ?>js/modules/news/news-full.js"></script>
<script src="<?php echo STYLE_URL; ?>js/wysibb/jquery.wysibb.min.js"></script>
<script src="<?php echo STYLE_URL; ?>js/wysibb/lang/ru.js"></script>
<link rel="stylesheet" href="<?php echo STYLE_URL; ?>js/wysibb/theme/default/wbbtheme.css"/>