<div class="item new-id attached">
	<div class="image">
		<img src="<?= $data['IMG']; ?>">
	</div>
	<div class="content">
		<a class="header">
			<i rel="tooltip" title="<?= $this->l10n->gettext('attached'); ?>" class="fa fa-tag"></i>
			<a href="<?= BASE_URL; ?>?mode=news&amp;id=<?= $data['ID']; ?>"><?= $data['TITLE']; ?>
				<?= $data['TITLE']; ?>
				<!-- <?= $data['ADMIN']; ?>
				<?= $data['LIKES']; ?> -->
			</a>
		</div>
	</div>
	<div class="meta">
		<span class="date">
			<?= $data['DATE']; ?>
		</span>
		<span class="category">
			<a href="<?= BASE_URL; ?>?mode=news&amp;cid=<?= $data['CID']; ?>" rel="tooltip" title="<?= $this->l10n->gettext('category'); ?>">
				<?= $data['CATEGORY']; ?>
			</a>
		</span>
	</div>
	<div class="description">
		<?= $data['TEXT']; ?>
	</div>
	<div class="extra">
		<div class="ui label views">
			<i class="eye icon"></i><?= $data['VIEWS']; ?>
		</div>
		<div class="ui label">
			<?= $data['COMMENTS']; ?>
		</div>
		
		<a class="ui right floated primary button" href="<?= BASE_URL; ?>?mode=news&amp;id=<?= $data['ID']; ?>">
			Подробнее <!-- TODO: Добавить фразу -->
			<i class="right chevron icon"></i>
		</a>
	</div>
</div>
