<div class="ui right floated mini buttons">

	<a class="ui primary button news-attach" href="#" data-id="<?= $data['ID']; ?>" data-tooltip="<?= $data['ATTACH']; ?>">
		<i class="thumbtack fitted icon"></i>
	</a>

	<a class="ui primary button news-edit" href="<?= ADMIN_URL; ?>&do=news&op=edit&id=<?= $data['ID']; ?>" data-tooltip="<?= $this->l10n->gettext('edit'); ?>">
		<i class="pencil fitted icon"></i>
	</a>

	<a class="ui negative button news-delete" href="#" data-id="<?= $data['ID']; ?>" data-tooltip="<?= $this->l10n->gettext('delete'); ?>">
		<i class="trash fitted icon"></i>
	</a>

</div>
